// AUTO-GENERATED by scripts/generate-types.js - do not hand-edit.
import type { OASISResponse, OASISSession } from './src/core/types';
import type { AuthModule } from './src/modules/Auth';
import type { AvatarModule } from './src/modules/Avatar';
import type { BridgeModule } from './src/modules/Bridge';
import type { ChatModule } from './src/modules/Chat';
import type { ClanModule } from './src/modules/Clan';
import type { CompetitionModule } from './src/modules/Competition';
import type { DataModule } from './src/modules/Data';
import type { EOSIOModule } from './src/modules/EOSIO';
import type { EggsModule } from './src/modules/Eggs';
import type { FilesModule } from './src/modules/Files';
import type { GiftsModule } from './src/modules/Gifts';
import type { HealthModule } from './src/modules/Health';
import type { HolochainModule } from './src/modules/Holochain';
import type { HyperDriveModule } from './src/modules/HyperDrive';
import type { KarmaModule } from './src/modules/Karma';
import type { KeysModule } from './src/modules/Keys';
import type { MapModule } from './src/modules/Map';
import type { MessagingModule } from './src/modules/Messaging';
import type { NftModule } from './src/modules/Nft';
import type { OLandModule } from './src/modules/OLand';
import type { ONETModule } from './src/modules/ONET';
import type { ONODEModule } from './src/modules/ONODE';
import type { ProviderModule } from './src/modules/Provider';
import type { SearchModule } from './src/modules/Search';
import type { SeedsModule } from './src/modules/Seeds';
import type { SettingsModule } from './src/modules/Settings';
import type { ShareModule } from './src/modules/Share';
import type { SocialModule } from './src/modules/Social';
import type { SolanaModule } from './src/modules/Solana';
import type { StatsModule } from './src/modules/Stats';
import type { SubscriptionModule } from './src/modules/Subscription';
import type { VideoModule } from './src/modules/Video';
import type { WalletModule } from './src/modules/Wallet';

export type { OASISResponse, OASISSession };

export interface OASISClientOptions {
  baseUrl?: string;
  persistSession?: boolean;
  fetchImpl?: typeof fetch;
}

export declare class HttpClient {
  constructor(options?: { baseUrl?: string; tokenStore?: unknown; fetchImpl?: typeof fetch });
  setBaseUrl(baseUrl: string): void;
  request(verb: 'GET' | 'POST' | 'PUT' | 'DELETE', path: string, options?: Record<string, any>): Promise<OASISResponse>;
  get(path: string, options?: Record<string, any>): Promise<OASISResponse>;
  post(path: string, options?: Record<string, any>): Promise<OASISResponse>;
  put(path: string, options?: Record<string, any>): Promise<OASISResponse>;
  delete(path: string, options?: Record<string, any>): Promise<OASISResponse>;
}

export declare class TokenStore {
  constructor(options?: { persist?: boolean });
  getSession(): OASISSession | null;
  getToken(): string | null;
  setSession(session: OASISSession | null): void;
  clear(): void;
}

export declare const DEFAULT_BASE_URL: string;

export declare class OASISClient {
  constructor(options?: OASISClientOptions);
  readonly http: HttpClient;
  readonly tokenStore: TokenStore;
  readonly auth: AuthModule;
  readonly avatar: AvatarModule;
  readonly bridge: BridgeModule;
  readonly chat: ChatModule;
  readonly clan: ClanModule;
  readonly competition: CompetitionModule;
  readonly data: DataModule;
  readonly eOSIO: EOSIOModule;
  readonly eggs: EggsModule;
  readonly files: FilesModule;
  readonly gifts: GiftsModule;
  readonly health: HealthModule;
  readonly holochain: HolochainModule;
  readonly hyperDrive: HyperDriveModule;
  readonly karma: KarmaModule;
  readonly keys: KeysModule;
  readonly map: MapModule;
  readonly messaging: MessagingModule;
  readonly nft: NftModule;
  readonly oLand: OLandModule;
  readonly oNET: ONETModule;
  readonly oNODE: ONODEModule;
  readonly provider: ProviderModule;
  readonly search: SearchModule;
  readonly seeds: SeedsModule;
  readonly settings: SettingsModule;
  readonly share: ShareModule;
  readonly social: SocialModule;
  readonly solana: SolanaModule;
  readonly stats: StatsModule;
  readonly subscription: SubscriptionModule;
  readonly video: VideoModule;
  readonly wallet: WalletModule;
  setBaseUrl(baseUrl: string): void;
  setToken(jwtToken: string, sessionExtras?: Partial<OASISSession>): void;
}

export default OASISClient;
