// AUTO-GENERATED by scripts/generate-types.js - do not hand-edit.
import type { OASISResponse } from '../core/types';

export declare class AvatarModule {
  constructor(http: unknown);

  /** POST api/avatar/inventory */
  addItemToAvatarInventory(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/avatar/add-karma-to-avatar/{avatarId} */
  addKarmaToAvatar(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/avatar/add-xp */
  addXp(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/avatar/authenticate */
  authenticate(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/avatar/inventory/{itemId}/has */
  avatarHasItem(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/avatar/inventory/has-by-name */
  avatarHasItemByName(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/avatar/create/{model} */
  create(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/avatar/{avatarId}/sessions */
  createAvatarSession(args?: Record<string, any>): Promise<OASISResponse>;

  /** DELETE api/avatar/{id:Guid} */
  delete(args?: Record<string, any>): Promise<OASISResponse>;

  /** DELETE api/avatar/delete-by-email/{email} */
  deleteByEmail(args?: Record<string, any>): Promise<OASISResponse>;

  /** DELETE api/avatar/delete-by-username/{username} */
  deleteByUsername(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/avatar/forgot-password */
  forgotPassword(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/avatar/get-all-avatars */
  getAll(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/avatar/get-all-avatar-details */
  getAllAvatarDetails(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/avatar/get-all-avatar-names/{includeUsernames}/{includeIds} */
  getAllAvatarNames(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/avatar/get-all-avatar-names-grouped-by-name/{includeUsernames}/{includeIds} */
  getAllAvatarNamesGroupedByName(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/avatar/get-avatar-detail-by-id/{id:guid} */
  getAvatarDetail(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/avatar/get-avatar-detail-by-email/{email} */
  getAvatarDetailByEmail(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/avatar/get-avatar-detail-by-username/{username} */
  getAvatarDetailByUsername(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/avatar/inventory */
  getAvatarInventory(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/avatar/inventory/{itemId} */
  getAvatarInventoryItem(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/avatar/get-avatar-portrait-by-email/{email} */
  getAvatarPortraitByEmail(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/avatar/get-avatar-portrait/{id} */
  getAvatarPortraitById(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/avatar/get-avatar-portrait-by-username/{username} */
  getAvatarPortraitByUsername(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/avatar/{avatarId}/sessions */
  getAvatarSessions(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/avatar/{avatarId}/sessions/stats */
  getAvatarSessionStats(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/avatar/get-by-email/{email} */
  getByEmail(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/avatar/get-by-id/{id} */
  getById(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/avatar/get-by-username/{username} */
  getByUsername(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/avatar/get-logged-in-avatar */
  getLoggedInAvatar(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/avatar/get-logged-in-avatar-with-xp */
  getLoggedInAvatarWithXp(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/avatar/get-terms */
  getTerms(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/avatar/get-uma-json-by-email/{email} */
  getUmaJsonByEmail(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/avatar/get-uma-json-by-id/{id} */
  getUmaJsonById(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/avatar/get-uma-json-by-username/{username} */
  getUmaJsonByUsername(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/avatar/{avatarId}/{eosioAccountName} */
  linkEOSIOAccountToAvatar(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/avatar/{avatarId}/{holochainAgentID} */
  linkHolochainAgentIDToAvatar(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/avatar/{id:Guid}/{telosAccountName} */
  linkTelosAccountToAvatar(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/avatar/ */
  linkTelosAccountToAvatar2(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/avatar/{avatarId}/sessions/logout-all */
  logoutAllAvatarSessions(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/avatar/{avatarId}/sessions/logout */
  logoutAvatarSessions(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/avatar/refresh-token */
  refreshToken(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/avatar/register */
  register(args?: Record<string, any>): Promise<OASISResponse>;

  /** DELETE api/avatar/inventory/{itemId} */
  removeItemFromAvatarInventory(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/avatar/remove-karma-from-avatar/{avatarId} */
  removeKarmaFromAvatar(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/avatar/reset-password */
  resetPassword(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/avatar/revoke-token */
  revokeToken(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/avatar/search */
  searchAvatar(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/avatar/inventory/search */
  searchAvatarInventory(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/avatar/inventory/send-to-avatar */
  sendItemToAvatar(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/avatar/inventory/send-to-clan */
  sendItemToClan(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/avatar/set-active-quest */
  setActiveQuest(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/avatar/update-by-id/{id} */
  update(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/avatar/update-avatar-detail-by-id/{id} */
  updateAvatarDetail(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/avatar/update-avatar-detail-by-email/{email} */
  updateAvatarDetailByEmail(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/avatar/update-avatar-detail-by-username/{username} */
  updateAvatarDetailByUsername(args?: Record<string, any>): Promise<OASISResponse>;

  /** PUT api/avatar/{avatarId}/sessions/{sessionId} */
  updateAvatarSession(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/avatar/update-by-email/{email} */
  updateByEmail(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/avatar/update-by-username/{username} */
  updateByUsername(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/avatar/upload-avatar-portrait */
  uploadAvatarPortrait(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/avatar/validate-reset-token */
  validateResetToken(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/avatar/verify-email */
  verifyEmail(args?: Record<string, any>): Promise<OASISResponse>;
}
