'use strict';

// AUTO-GENERATED by scripts/generate-modules.js from endpoints.json - do not hand-edit.
// Regenerate with: node scripts/generate-modules.js

const { makeOperation } = require('../core/routeHelper');

/**
 * Generated wrapper for api/avatar (source: ONODE WebAPI AvatarController.cs).
 * Every method takes a single args object: path-template tokens (e.g. {id})
 * are consumed from it automatically; any remaining keys are sent as the
 * query string (GET/DELETE) or JSON body (POST/PUT).
 */
class AvatarModule {
  constructor(http) {
    this._http = http;

    // Post api/avatar/inventory
    this.addItemToAvatarInventory = makeOperation(http, "api/avatar", "POST", "inventory");
    // Post api/avatar/add-karma-to-avatar/{avatarId}
    this.addKarmaToAvatar = makeOperation(http, "api/avatar", "POST", "add-karma-to-avatar/{avatarId}");
    // Post api/avatar/add-xp
    this.addXp = makeOperation(http, "api/avatar", "POST", "add-xp");
    // Post api/avatar/authenticate
    this.authenticate = makeOperation(http, "api/avatar", "POST", "authenticate");
    // Get api/avatar/inventory/{itemId}/has
    this.avatarHasItem = makeOperation(http, "api/avatar", "GET", "inventory/{itemId}/has");
    // Get api/avatar/inventory/has-by-name
    this.avatarHasItemByName = makeOperation(http, "api/avatar", "GET", "inventory/has-by-name");
    // Post api/avatar/create/{model}
    this.create = makeOperation(http, "api/avatar", "POST", "create/{model}");
    // Post api/avatar/{avatarId}/sessions
    this.createAvatarSession = makeOperation(http, "api/avatar", "POST", "{avatarId}/sessions");
    // Delete api/avatar/{id:Guid}
    this.delete = makeOperation(http, "api/avatar", "DELETE", "{id:Guid}");
    // Delete api/avatar/delete-by-email/{email}
    this.deleteByEmail = makeOperation(http, "api/avatar", "DELETE", "delete-by-email/{email}");
    // Delete api/avatar/delete-by-username/{username}
    this.deleteByUsername = makeOperation(http, "api/avatar", "DELETE", "delete-by-username/{username}");
    // Post api/avatar/forgot-password
    this.forgotPassword = makeOperation(http, "api/avatar", "POST", "forgot-password");
    // Get api/avatar/get-all-avatars
    this.getAll = makeOperation(http, "api/avatar", "GET", "get-all-avatars");
    // Get api/avatar/get-all-avatar-details
    this.getAllAvatarDetails = makeOperation(http, "api/avatar", "GET", "get-all-avatar-details");
    // Get api/avatar/get-all-avatar-names/{includeUsernames}/{includeIds}
    this.getAllAvatarNames = makeOperation(http, "api/avatar", "GET", "get-all-avatar-names/{includeUsernames}/{includeIds}");
    // Get api/avatar/get-all-avatar-names-grouped-by-name/{includeUsernames}/{includeIds}
    this.getAllAvatarNamesGroupedByName = makeOperation(http, "api/avatar", "GET", "get-all-avatar-names-grouped-by-name/{includeUsernames}/{includeIds}");
    // Get api/avatar/get-avatar-detail-by-id/{id:guid}
    this.getAvatarDetail = makeOperation(http, "api/avatar", "GET", "get-avatar-detail-by-id/{id:guid}");
    // Get api/avatar/get-avatar-detail-by-email/{email}
    this.getAvatarDetailByEmail = makeOperation(http, "api/avatar", "GET", "get-avatar-detail-by-email/{email}");
    // Get api/avatar/get-avatar-detail-by-username/{username}
    this.getAvatarDetailByUsername = makeOperation(http, "api/avatar", "GET", "get-avatar-detail-by-username/{username}");
    // Get api/avatar/inventory
    this.getAvatarInventory = makeOperation(http, "api/avatar", "GET", "inventory");
    // Get api/avatar/inventory/{itemId}
    this.getAvatarInventoryItem = makeOperation(http, "api/avatar", "GET", "inventory/{itemId}");
    // Get api/avatar/get-avatar-portrait-by-email/{email}
    this.getAvatarPortraitByEmail = makeOperation(http, "api/avatar", "GET", "get-avatar-portrait-by-email/{email}");
    // Get api/avatar/get-avatar-portrait/{id}
    this.getAvatarPortraitById = makeOperation(http, "api/avatar", "GET", "get-avatar-portrait/{id}");
    // Get api/avatar/get-avatar-portrait-by-username/{username}
    this.getAvatarPortraitByUsername = makeOperation(http, "api/avatar", "GET", "get-avatar-portrait-by-username/{username}");
    // Get api/avatar/{avatarId}/sessions/stats
    this.getAvatarSessionStats = makeOperation(http, "api/avatar", "GET", "{avatarId}/sessions/stats");
    // Get api/avatar/{avatarId}/sessions
    this.getAvatarSessions = makeOperation(http, "api/avatar", "GET", "{avatarId}/sessions");
    // Get api/avatar/get-by-email/{email}
    this.getByEmail = makeOperation(http, "api/avatar", "GET", "get-by-email/{email}");
    // Get api/avatar/get-by-id/{id}
    this.getById = makeOperation(http, "api/avatar", "GET", "get-by-id/{id}");
    // Get api/avatar/get-by-username/{username}
    this.getByUsername = makeOperation(http, "api/avatar", "GET", "get-by-username/{username}");
    // Get api/avatar/get-logged-in-avatar
    this.getLoggedInAvatar = makeOperation(http, "api/avatar", "GET", "get-logged-in-avatar");
    // Get api/avatar/get-logged-in-avatar-with-xp
    this.getLoggedInAvatarWithXp = makeOperation(http, "api/avatar", "GET", "get-logged-in-avatar-with-xp");
    // Get api/avatar/get-terms
    this.getTerms = makeOperation(http, "api/avatar", "GET", "get-terms");
    // Get api/avatar/get-uma-json-by-email/{email}
    this.getUmaJsonByEmail = makeOperation(http, "api/avatar", "GET", "get-uma-json-by-email/{email}");
    // Get api/avatar/get-uma-json-by-id/{id}
    this.getUmaJsonById = makeOperation(http, "api/avatar", "GET", "get-uma-json-by-id/{id}");
    // Get api/avatar/get-uma-json-by-username/{username}
    this.getUmaJsonByUsername = makeOperation(http, "api/avatar", "GET", "get-uma-json-by-username/{username}");
    // Post api/avatar/{avatarId}/{eosioAccountName}
    this.linkEOSIOAccountToAvatar = makeOperation(http, "api/avatar", "POST", "{avatarId}/{eosioAccountName}");
    // Post api/avatar/{avatarId}/{holochainAgentID}
    this.linkHolochainAgentIDToAvatar = makeOperation(http, "api/avatar", "POST", "{avatarId}/{holochainAgentID}");
    // Post api/avatar/{id:Guid}/{telosAccountName}
    this.linkTelosAccountToAvatar = makeOperation(http, "api/avatar", "POST", "{id:Guid}/{telosAccountName}");
    // Post api/avatar/
    this.linkTelosAccountToAvatar2 = makeOperation(http, "api/avatar", "POST", "");
    // Post api/avatar/{avatarId}/sessions/logout-all
    this.logoutAllAvatarSessions = makeOperation(http, "api/avatar", "POST", "{avatarId}/sessions/logout-all");
    // Post api/avatar/{avatarId}/sessions/logout
    this.logoutAvatarSessions = makeOperation(http, "api/avatar", "POST", "{avatarId}/sessions/logout");
    // Post api/avatar/refresh-token
    this.refreshToken = makeOperation(http, "api/avatar", "POST", "refresh-token");
    // Post api/avatar/register
    this.register = makeOperation(http, "api/avatar", "POST", "register");
    // Delete api/avatar/inventory/{itemId}
    this.removeItemFromAvatarInventory = makeOperation(http, "api/avatar", "DELETE", "inventory/{itemId}");
    // Post api/avatar/remove-karma-from-avatar/{avatarId}
    this.removeKarmaFromAvatar = makeOperation(http, "api/avatar", "POST", "remove-karma-from-avatar/{avatarId}");
    // Post api/avatar/reset-password
    this.resetPassword = makeOperation(http, "api/avatar", "POST", "reset-password");
    // Post api/avatar/revoke-token
    this.revokeToken = makeOperation(http, "api/avatar", "POST", "revoke-token");
    // Post api/avatar/search
    this.searchAvatar = makeOperation(http, "api/avatar", "POST", "search");
    // Get api/avatar/inventory/search
    this.searchAvatarInventory = makeOperation(http, "api/avatar", "GET", "inventory/search");
    // Post api/avatar/inventory/send-to-avatar
    this.sendItemToAvatar = makeOperation(http, "api/avatar", "POST", "inventory/send-to-avatar");
    // Post api/avatar/inventory/send-to-clan
    this.sendItemToClan = makeOperation(http, "api/avatar", "POST", "inventory/send-to-clan");
    // Post api/avatar/set-active-quest
    this.setActiveQuest = makeOperation(http, "api/avatar", "POST", "set-active-quest");
    // Post api/avatar/update-by-id/{id}
    this.update = makeOperation(http, "api/avatar", "POST", "update-by-id/{id}");
    // Post api/avatar/update-avatar-detail-by-id/{id}
    this.updateAvatarDetail = makeOperation(http, "api/avatar", "POST", "update-avatar-detail-by-id/{id}");
    // Post api/avatar/update-avatar-detail-by-email/{email}
    this.updateAvatarDetailByEmail = makeOperation(http, "api/avatar", "POST", "update-avatar-detail-by-email/{email}");
    // Post api/avatar/update-avatar-detail-by-username/{username}
    this.updateAvatarDetailByUsername = makeOperation(http, "api/avatar", "POST", "update-avatar-detail-by-username/{username}");
    // Put api/avatar/{avatarId}/sessions/{sessionId}
    this.updateAvatarSession = makeOperation(http, "api/avatar", "PUT", "{avatarId}/sessions/{sessionId}");
    // Post api/avatar/update-by-email/{email}
    this.updateByEmail = makeOperation(http, "api/avatar", "POST", "update-by-email/{email}");
    // Post api/avatar/update-by-username/{username}
    this.updateByUsername = makeOperation(http, "api/avatar", "POST", "update-by-username/{username}");
    // Post api/avatar/upload-avatar-portrait
    this.uploadAvatarPortrait = makeOperation(http, "api/avatar", "POST", "upload-avatar-portrait");
    // Post api/avatar/validate-reset-token
    this.validateResetToken = makeOperation(http, "api/avatar", "POST", "validate-reset-token");
    // Get api/avatar/verify-email
    this.verifyEmail = makeOperation(http, "api/avatar", "GET", "verify-email");
  }
}

module.exports = { AvatarModule };
