// AUTO-GENERATED by scripts/generate-types.js - do not hand-edit.
import type { OASISResponse } from '../core/types';

export declare class BridgeModule {
  constructor(http: unknown);

  /** GET api/v1/bridge/orders/{orderId:guid}/check-balance */
  checkOrderBalance(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/v1/bridge/orders */
  createOrder(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/v1/bridge/orders/private */
  createPrivateOrder(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/v1/bridge/exchange-rate */
  getExchangeRate(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/v1/bridge/viewing-keys/audit */
  recordViewingKey(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/v1/bridge/proofs/verify */
  verifyProof(args?: Record<string, any>): Promise<OASISResponse>;
}
