'use strict';

// AUTO-GENERATED by scripts/generate-modules.js from endpoints.json - do not hand-edit.
// Regenerate with: node scripts/generate-modules.js

const { makeOperation } = require('../core/routeHelper');

/**
 * Generated wrapper for api/v1/bridge (source: ONODE WebAPI BridgeController.cs).
 * Every method takes a single args object: path-template tokens (e.g. {id})
 * are consumed from it automatically; any remaining keys are sent as the
 * query string (GET/DELETE) or JSON body (POST/PUT).
 */
class BridgeModule {
  constructor(http) {
    this._http = http;

    // Get api/v1/bridge/orders/{orderId:guid}/check-balance
    this.checkOrderBalance = makeOperation(http, "api/v1/bridge", "GET", "orders/{orderId:guid}/check-balance");
    // Post api/v1/bridge/orders
    this.createOrder = makeOperation(http, "api/v1/bridge", "POST", "orders");
    // Post api/v1/bridge/orders/private
    this.createPrivateOrder = makeOperation(http, "api/v1/bridge", "POST", "orders/private");
    // Get api/v1/bridge/exchange-rate
    this.getExchangeRate = makeOperation(http, "api/v1/bridge", "GET", "exchange-rate");
    // Post api/v1/bridge/viewing-keys/audit
    this.recordViewingKey = makeOperation(http, "api/v1/bridge", "POST", "viewing-keys/audit");
    // Post api/v1/bridge/proofs/verify
    this.verifyProof = makeOperation(http, "api/v1/bridge", "POST", "proofs/verify");
  }
}

module.exports = { BridgeModule };
