'use strict';

// AUTO-GENERATED by scripts/generate-modules.js from endpoints.json - do not hand-edit.
// Regenerate with: node scripts/generate-modules.js

const { makeOperation } = require('../core/routeHelper');

/**
 * Generated wrapper for api/cargo (source: ONODE WebAPI CargoController.cs).
 * Every method takes a single args object: path-template tokens (e.g. {id})
 * are consumed from it automatically; any remaining keys are sent as the
 * query string (GET/DELETE) or JSON body (POST/PUT).
 */
class CargoModule {
  constructor(http) {
    this._http = http;

    // POST api/cargo/AuthenticateAccount
    this.authenticateAccount = makeOperation(http, "api/cargo", "POST", "AuthenticateAccount");
    // POST api/cargo/AuthorizeAccount
    this.authorizeAccount = makeOperation(http, "api/cargo", "POST", "AuthorizeAccount");
    // POST api/cargo/CancelSale
    this.cancelCargoSale = makeOperation(http, "api/cargo", "POST", "CancelSale");
    // GET api/cargo/GetCollectiblesListByProjectId
    this.collectiblesListByProjectId = makeOperation(http, "api/cargo", "GET", "GetCollectiblesListByProjectId");
    // GET api/cargo/GetOrders
    this.getCargoOrders = makeOperation(http, "api/cargo", "GET", "GetOrders");
    // GET api/cargo/GetUserTokensByContract
    this.getUserTokensByContract = makeOperation(http, "api/cargo", "GET", "GetUserTokensByContract");
    // POST api/cargo/PurchaseSale
    this.purchaseCargoSale = makeOperation(http, "api/cargo", "POST", "PurchaseSale");
  }
}

module.exports = { CargoModule };
