'use strict';

// AUTO-GENERATED by scripts/generate-modules.js from endpoints.json - do not hand-edit.
// Regenerate with: node scripts/generate-modules.js

const { makeOperation } = require('../core/routeHelper');

/**
 * Generated wrapper for api/chat (source: ONODE WebAPI ChatController.cs).
 * Every method takes a single args object: path-template tokens (e.g. {id})
 * are consumed from it automatically; any remaining keys are sent as the
 * query string (GET/DELETE) or JSON body (POST/PUT).
 */
class ChatModule {
  constructor(http) {
    this._http = http;

    // GET api/chat/history/{sessionId}
    this.getChatHistory = makeOperation(http, "api/chat", "GET", "history/{sessionId}");
    // POST api/chat/send-message/{sessionId}
    this.sendMessage = makeOperation(http, "api/chat", "POST", "send-message/{sessionId}");
    // POST api/chat/start-new-chat-session
    this.startNewChatSession = makeOperation(http, "api/chat", "POST", "start-new-chat-session");
  }
}

module.exports = { ChatModule };
