// AUTO-GENERATED by scripts/generate-types.js - do not hand-edit.
import type { OASISResponse } from '../core/types';

export declare class ChatModule {
  constructor(http: unknown);

  /** GET api/chat/history/{sessionId} */
  getChatHistory(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/chat/send-message/{sessionId} */
  sendMessage(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/chat/start-new-chat-session */
  startNewChatSession(args?: Record<string, any>): Promise<OASISResponse>;
}
