// AUTO-GENERATED by scripts/generate-types.js - do not hand-edit.
import type { OASISResponse } from '../core/types';

export declare class ClanModule {
  constructor(http: unknown);

  /** POST api/clan/{clanId:guid}/members/{avatarId:guid} */
  addAvatarToClan(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/clan/ */
  create(args?: Record<string, any>): Promise<OASISResponse>;

  /** DELETE api/clan/{clanId:guid} */
  delete(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/clan/{clanId:guid}/inventory */
  getClanInventory(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/clan/{clanId:guid}/members */
  getMembers(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/clan/ */
  list(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/clan/{clanId:guid} */
  load(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/clan/by-name */
  loadByName(args?: Record<string, any>): Promise<OASISResponse>;

  /** DELETE api/clan/{clanId:guid}/members/{avatarId:guid} */
  removeAvatarFromClan(args?: Record<string, any>): Promise<OASISResponse>;

  /** PUT api/clan/{clanId:guid} */
  update(args?: Record<string, any>): Promise<OASISResponse>;
}
