'use strict';

// AUTO-GENERATED by scripts/generate-modules.js from endpoints.json - do not hand-edit.
// Regenerate with: node scripts/generate-modules.js

const { makeOperation } = require('../core/routeHelper');

/**
 * Generated wrapper for api/clan (source: ONODE WebAPI ClanController.cs).
 * Every method takes a single args object: path-template tokens (e.g. {id})
 * are consumed from it automatically; any remaining keys are sent as the
 * query string (GET/DELETE) or JSON body (POST/PUT).
 */
class ClanModule {
  constructor(http) {
    this._http = http;

    // POST api/clan/{clanId:guid}/members/{avatarId:guid}
    this.addAvatarToClan = makeOperation(http, "api/clan", "POST", "{clanId:guid}/members/{avatarId:guid}");
    // POST api/clan/
    this.create = makeOperation(http, "api/clan", "POST", "");
    // DELETE api/clan/{clanId:guid}
    this.delete = makeOperation(http, "api/clan", "DELETE", "{clanId:guid}");
    // GET api/clan/{clanId:guid}/inventory
    this.getClanInventory = makeOperation(http, "api/clan", "GET", "{clanId:guid}/inventory");
    // GET api/clan/{clanId:guid}/members
    this.getMembers = makeOperation(http, "api/clan", "GET", "{clanId:guid}/members");
    // GET api/clan/
    this.list = makeOperation(http, "api/clan", "GET", "");
    // GET api/clan/{clanId:guid}
    this.load = makeOperation(http, "api/clan", "GET", "{clanId:guid}");
    // GET api/clan/by-name
    this.loadByName = makeOperation(http, "api/clan", "GET", "by-name");
    // DELETE api/clan/{clanId:guid}/members/{avatarId:guid}
    this.removeAvatarFromClan = makeOperation(http, "api/clan", "DELETE", "{clanId:guid}/members/{avatarId:guid}");
    // PUT api/clan/{clanId:guid}
    this.update = makeOperation(http, "api/clan", "PUT", "{clanId:guid}");
  }
}

module.exports = { ClanModule };
