'use strict';

// AUTO-GENERATED by scripts/generate-modules.js from endpoints.json - do not hand-edit.
// Regenerate with: node scripts/generate-modules.js

const { makeOperation } = require('../core/routeHelper');

/**
 * Generated wrapper for api/core (source: ONODE WebAPI CoreController.cs).
 * Every method takes a single args object: path-template tokens (e.g. {id})
 * are consumed from it automatically; any remaining keys are sent as the
 * query string (GET/DELETE) or JSON body (POST/PUT).
 */
class CoreModule {
  constructor(http) {
    this._http = http;

    // POST api/core/generate-moon
    this.generateMoon = makeOperation(http, "api/core", "POST", "generate-moon");
    // GET api/core/config
    this.getSystemConfig = makeOperation(http, "api/core", "GET", "config");
    // GET api/core/health
    this.getSystemHealth = makeOperation(http, "api/core", "GET", "health");
  }
}

module.exports = { CoreModule };
