// AUTO-GENERATED by scripts/generate-types.js - do not hand-edit.
import type { OASISResponse } from '../core/types';

export declare class DataModule {
  constructor(http: unknown);

  /** DELETE api/data/delete-holon */
  deleteHolon(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/data/load-all-holons */
  loadAllHolons(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/data/load-data */
  loadData(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/data/load-file */
  loadFile(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/data/load-holon */
  loadHolon(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/data/load-holons-for-parent */
  loadHolonsForParent(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/data/save-data */
  saveData(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/data/save-file */
  saveFile(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/data/save-holon */
  saveHolon(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/data/save-holon-off-chain */
  saveHolonOffChain(args?: Record<string, any>): Promise<OASISResponse>;
}
