'use strict';

// AUTO-GENERATED by scripts/generate-modules.js from endpoints.json - do not hand-edit.
// Regenerate with: node scripts/generate-modules.js

const { makeOperation } = require('../core/routeHelper');

/**
 * Generated wrapper for api/data (source: ONODE WebAPI DataController.cs).
 * Every method takes a single args object: path-template tokens (e.g. {id})
 * are consumed from it automatically; any remaining keys are sent as the
 * query string (GET/DELETE) or JSON body (POST/PUT).
 */
class DataModule {
  constructor(http) {
    this._http = http;

    // DELETE api/data/delete-holon
    this.deleteHolon = makeOperation(http, "api/data", "DELETE", "delete-holon");
    // POST api/data/load-all-holons
    this.loadAllHolons = makeOperation(http, "api/data", "POST", "load-all-holons");
    // POST api/data/load-data
    this.loadData = makeOperation(http, "api/data", "POST", "load-data");
    // POST api/data/load-file
    this.loadFile = makeOperation(http, "api/data", "POST", "load-file");
    // POST api/data/load-holon
    this.loadHolon = makeOperation(http, "api/data", "POST", "load-holon");
    // POST api/data/load-holons-for-parent
    this.loadHolonsForParent = makeOperation(http, "api/data", "POST", "load-holons-for-parent");
    // POST api/data/save-data
    this.saveData = makeOperation(http, "api/data", "POST", "save-data");
    // POST api/data/save-file
    this.saveFile = makeOperation(http, "api/data", "POST", "save-file");
    // POST api/data/save-holon
    this.saveHolon = makeOperation(http, "api/data", "POST", "save-holon");
    // POST api/data/save-holon-off-chain
    this.saveHolonOffChain = makeOperation(http, "api/data", "POST", "save-holon-off-chain");
  }
}

module.exports = { DataModule };
