'use strict';

// AUTO-GENERATED by scripts/generate-modules.js from endpoints.json - do not hand-edit.
// Regenerate with: node scripts/generate-modules.js

const { makeOperation } = require('../core/routeHelper');

/**
 * Generated wrapper for api/eggs (source: ONODE WebAPI EggsController.cs).
 * Every method takes a single args object: path-template tokens (e.g. {id})
 * are consumed from it automatically; any remaining keys are sent as the
 * query string (GET/DELETE) or JSON body (POST/PUT).
 */
class EggsModule {
  constructor(http) {
    this._http = http;

    // Post api/eggs/discover
    this.discoverEgg = makeOperation(http, "api/eggs", "POST", "discover");
    // Get api/eggs/get-all-eggs
    this.getAllEggs = makeOperation(http, "api/eggs", "GET", "get-all-eggs");
    // Get api/eggs/get-current-egg-quest-leader-board
    this.getCurrentEggQuestLeaderBoard = makeOperation(http, "api/eggs", "GET", "get-current-egg-quest-leader-board");
    // Get api/eggs/get-current-egg-quests
    this.getCurrentEggQuests = makeOperation(http, "api/eggs", "GET", "get-current-egg-quests");
    // Get api/eggs/my-eggs
    this.getMyEggs = makeOperation(http, "api/eggs", "GET", "my-eggs");
    // Post api/eggs/hatch/{eggId}
    this.hatchEgg = makeOperation(http, "api/eggs", "POST", "hatch/{eggId}");
  }
}

module.exports = { EggsModule };
