// AUTO-GENERATED by scripts/generate-types.js - do not hand-edit.
import type { OASISResponse } from '../core/types';

export declare class EggsModule {
  constructor(http: unknown);

  /** POST api/eggs/discover */
  discoverEgg(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/eggs/get-all-eggs */
  getAllEggs(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/eggs/get-current-egg-quest-leader-board */
  getCurrentEggQuestLeaderBoard(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/eggs/get-current-egg-quests */
  getCurrentEggQuests(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/eggs/my-eggs */
  getMyEggs(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/eggs/hatch/{eggId} */
  hatchEgg(args?: Record<string, any>): Promise<OASISResponse>;
}
