// AUTO-GENERATED by scripts/generate-types.js - do not hand-edit.
import type { OASISResponse } from '../core/types';

export declare class EOSIOModule {
  constructor(http: unknown);

  /** GET api/eosio/get-avatar-for-eosio-account-name */
  getAvatarForEOSIOAccountName(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/eosio/get-avatar-id-for-eosio-account-name */
  getAvatarIdForEOSIOAccountName(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/eosio/get-balance-for-avatar */
  getBalanceForAvatar(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/eosio/get-balance-for-eosio-account */
  getBalanceForEOSIOAccount(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/eosio/get-eosio-account */
  getEOSIOAccount(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/eosio/get-eosio-account-for-avatar */
  getEOSIOAccountForAvatar(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/eosio/get-eosio-account-name-for-avatar */
  getEOSIOAccountNamesForAvatar(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/eosio/get-eosio-account-private-key-for-avatar */
  getTelosAccountPrivateKeyForAvatar(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/eosio/{avatarId}/{eosioAccountName} */
  linkEOSIOAccountToAvatar(args?: Record<string, any>): Promise<OASISResponse>;
}
