'use strict';

// AUTO-GENERATED by scripts/generate-modules.js from endpoints.json - do not hand-edit.
// Regenerate with: node scripts/generate-modules.js

const { makeOperation } = require('../core/routeHelper');

/**
 * Generated wrapper for api/eosio (source: ONODE WebAPI EOSIOController.cs).
 * Every method takes a single args object: path-template tokens (e.g. {id})
 * are consumed from it automatically; any remaining keys are sent as the
 * query string (GET/DELETE) or JSON body (POST/PUT).
 */
class EOSIOModule {
  constructor(http) {
    this._http = http;

    // GET api/eosio/get-avatar-for-eosio-account-name
    this.getAvatarForEOSIOAccountName = makeOperation(http, "api/eosio", "GET", "get-avatar-for-eosio-account-name");
    // GET api/eosio/get-avatar-id-for-eosio-account-name
    this.getAvatarIdForEOSIOAccountName = makeOperation(http, "api/eosio", "GET", "get-avatar-id-for-eosio-account-name");
    // GET api/eosio/get-balance-for-avatar
    this.getBalanceForAvatar = makeOperation(http, "api/eosio", "GET", "get-balance-for-avatar");
    // GET api/eosio/get-balance-for-eosio-account
    this.getBalanceForEOSIOAccount = makeOperation(http, "api/eosio", "GET", "get-balance-for-eosio-account");
    // GET api/eosio/get-eosio-account
    this.getEOSIOAccount = makeOperation(http, "api/eosio", "GET", "get-eosio-account");
    // GET api/eosio/get-eosio-account-for-avatar
    this.getEOSIOAccountForAvatar = makeOperation(http, "api/eosio", "GET", "get-eosio-account-for-avatar");
    // GET api/eosio/get-eosio-account-name-for-avatar
    this.getEOSIOAccountNamesForAvatar = makeOperation(http, "api/eosio", "GET", "get-eosio-account-name-for-avatar");
    // GET api/eosio/get-eosio-account-private-key-for-avatar
    this.getTelosAccountPrivateKeyForAvatar = makeOperation(http, "api/eosio", "GET", "get-eosio-account-private-key-for-avatar");
    // POST api/eosio/{avatarId}/{eosioAccountName}
    this.linkEOSIOAccountToAvatar = makeOperation(http, "api/eosio", "POST", "{avatarId}/{eosioAccountName}");
  }
}

module.exports = { EOSIOModule };
