// AUTO-GENERATED by scripts/generate-types.js - do not hand-edit.
import type { OASISResponse } from '../core/types';

export declare class FilesModule {
  constructor(http: unknown);

  /** DELETE api/files/delete-file/{fileId} */
  deleteFile(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/files/download-file/{fileId} */
  downloadFile(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/files/get-all-files-stored-for-current-logged-in-avatar */
  getAllFilesStoredForCurrentLoggedInAvatar(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/files/file-metadata/{fileId} */
  getFileMetadata(args?: Record<string, any>): Promise<OASISResponse>;

  /** PUT api/files/update-file-metadata/{fileId} */
  updateFileMetadata(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/files/upload-file */
  uploadFile(args?: Record<string, any>): Promise<OASISResponse>;
}
