'use strict';

// AUTO-GENERATED by scripts/generate-modules.js from endpoints.json - do not hand-edit.
// Regenerate with: node scripts/generate-modules.js

const { makeOperation } = require('../core/routeHelper');

/**
 * Generated wrapper for api/files (source: ONODE WebAPI FilesController.cs).
 * Every method takes a single args object: path-template tokens (e.g. {id})
 * are consumed from it automatically; any remaining keys are sent as the
 * query string (GET/DELETE) or JSON body (POST/PUT).
 */
class FilesModule {
  constructor(http) {
    this._http = http;

    // Delete api/files/delete-file/{fileId}
    this.deleteFile = makeOperation(http, "api/files", "DELETE", "delete-file/{fileId}");
    // Get api/files/download-file/{fileId}
    this.downloadFile = makeOperation(http, "api/files", "GET", "download-file/{fileId}");
    // Get api/files/get-all-files-stored-for-current-logged-in-avatar
    this.getAllFilesStoredForCurrentLoggedInAvatar = makeOperation(http, "api/files", "GET", "get-all-files-stored-for-current-logged-in-avatar");
    // Get api/files/file-metadata/{fileId}
    this.getFileMetadata = makeOperation(http, "api/files", "GET", "file-metadata/{fileId}");
    // Put api/files/update-file-metadata/{fileId}
    this.updateFileMetadata = makeOperation(http, "api/files", "PUT", "update-file-metadata/{fileId}");
    // Post api/files/upload-file
    this.uploadFile = makeOperation(http, "api/files", "POST", "upload-file");
  }
}

module.exports = { FilesModule };
