// AUTO-GENERATED by scripts/generate-types.js - do not hand-edit.
import type { OASISResponse } from '../core/types';

export declare class GiftsModule {
  constructor(http: unknown);

  /** GET api/gifts/history */
  getGiftHistory(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/gifts/stats */
  getGiftStats(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/gifts/my-gifts */
  getMyGifts(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/gifts/open-gift/{giftId} */
  openGift(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/gifts/receive-gift/{giftId} */
  receiveGift(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/gifts/send-gift/{toAvatarId} */
  sendGift(args?: Record<string, any>): Promise<OASISResponse>;
}
