'use strict';

// AUTO-GENERATED by scripts/generate-modules.js from endpoints.json - do not hand-edit.
// Regenerate with: node scripts/generate-modules.js

const { makeOperation } = require('../core/routeHelper');

/**
 * Generated wrapper for api/gifts (source: ONODE WebAPI GiftsController.cs).
 * Every method takes a single args object: path-template tokens (e.g. {id})
 * are consumed from it automatically; any remaining keys are sent as the
 * query string (GET/DELETE) or JSON body (POST/PUT).
 */
class GiftsModule {
  constructor(http) {
    this._http = http;

    // Get api/gifts/history
    this.getGiftHistory = makeOperation(http, "api/gifts", "GET", "history");
    // Get api/gifts/stats
    this.getGiftStats = makeOperation(http, "api/gifts", "GET", "stats");
    // Get api/gifts/my-gifts
    this.getMyGifts = makeOperation(http, "api/gifts", "GET", "my-gifts");
    // Post api/gifts/open-gift/{giftId}
    this.openGift = makeOperation(http, "api/gifts", "POST", "open-gift/{giftId}");
    // Post api/gifts/receive-gift/{giftId}
    this.receiveGift = makeOperation(http, "api/gifts", "POST", "receive-gift/{giftId}");
    // Post api/gifts/send-gift/{toAvatarId}
    this.sendGift = makeOperation(http, "api/gifts", "POST", "send-gift/{toAvatarId}");
  }
}

module.exports = { GiftsModule };
