'use strict';

// AUTO-GENERATED by scripts/generate-modules.js from endpoints.json - do not hand-edit.
// Regenerate with: node scripts/generate-modules.js

const { makeOperation } = require('../core/routeHelper');

/**
 * Generated wrapper for api/holochain (source: ONODE WebAPI HolochainController.cs).
 * Every method takes a single args object: path-template tokens (e.g. {id})
 * are consumed from it automatically; any remaining keys are sent as the
 * query string (GET/DELETE) or JSON body (POST/PUT).
 */
class HolochainModule {
  constructor(http) {
    this._http = http;

    // Get api/holochain/get-avatar-for-holochain-agentid
    this.getAvatarForHolochainAgentId = makeOperation(http, "api/holochain", "GET", "get-avatar-for-holochain-agentid");
    // Get api/holochain/get-avatar-id-for-holochain-agentid
    this.getAvatarIdForHolochainAgentId = makeOperation(http, "api/holochain", "GET", "get-avatar-id-for-holochain-agentid");
    // Get api/holochain/get-holo-fuel-balance-for-agentId
    this.getHoloFuelBalanceForAgentId = makeOperation(http, "api/holochain", "GET", "get-holo-fuel-balance-for-agentId");
    // Get api/holochain/get-holo-fuel-balance-for-avatar
    this.getHoloFuelBalanceForAvatar = makeOperation(http, "api/holochain", "GET", "get-holo-fuel-balance-for-avatar");
    // Get api/holochain/get-holochain-agentids-for-avatar
    this.getHolochainAgentIdsForAvatar = makeOperation(http, "api/holochain", "GET", "get-holochain-agentids-for-avatar");
    // Get api/holochain/get-holochain-agent-private-keys-for-avatar
    this.getHolochainAgentPrivateKeysForAvatar = makeOperation(http, "api/holochain", "GET", "get-holochain-agent-private-keys-for-avatar");
    // Post api/holochain/{avatarId}/{holochainAgentId}
    this.linkHolochainAgentIdToAvatar = makeOperation(http, "api/holochain", "POST", "{avatarId}/{holochainAgentId}");
  }
}

module.exports = { HolochainModule };
