// AUTO-GENERATED by scripts/generate-types.js - do not hand-edit.
import type { OASISResponse } from '../core/types';

export declare class HolochainModule {
  constructor(http: unknown);

  /** GET api/holochain/get-avatar-for-holochain-agentid */
  getAvatarForHolochainAgentId(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/holochain/get-avatar-id-for-holochain-agentid */
  getAvatarIdForHolochainAgentId(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/holochain/get-holochain-agentids-for-avatar */
  getHolochainAgentIdsForAvatar(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/holochain/get-holochain-agent-private-keys-for-avatar */
  getHolochainAgentPrivateKeysForAvatar(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/holochain/get-holo-fuel-balance-for-agentId */
  getHoloFuelBalanceForAgentId(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/holochain/get-holo-fuel-balance-for-avatar */
  getHoloFuelBalanceForAvatar(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/holochain/{avatarId}/{holochainAgentId} */
  linkHolochainAgentIdToAvatar(args?: Record<string, any>): Promise<OASISResponse>;
}
