'use strict';

// AUTO-GENERATED by scripts/generate-modules.js from endpoints.json - do not hand-edit.
// Regenerate with: node scripts/generate-modules.js

const { makeOperation } = require('../core/routeHelper');

/**
 * Generated wrapper for api/hyperdrive (source: ONODE WebAPI HyperDriveController.cs).
 * Every method takes a single args object: path-template tokens (e.g. {id})
 * are consumed from it automatically; any remaining keys are sent as the
 * query string (GET/DELETE) or JSON body (POST/PUT).
 */
class HyperDriveModule {
  constructor(http) {
    this._http = http;

    // GET api/hyperdrive/quota/status
    this.checkQuotaStatus = makeOperation(http, "api/hyperdrive", "GET", "quota/status");
    // POST api/hyperdrive/failover/triggers
    this.createFailoverTrigger = makeOperation(http, "api/hyperdrive", "POST", "failover/triggers");
    // POST api/hyperdrive/subscription/quota-notifications
    this.createQuotaNotification = makeOperation(http, "api/hyperdrive", "POST", "subscription/quota-notifications");
    // POST api/hyperdrive/replication/triggers
    this.createReplicationTrigger = makeOperation(http, "api/hyperdrive", "POST", "replication/triggers");
    // POST api/hyperdrive/subscription/usage-alerts
    this.createUsageAlert = makeOperation(http, "api/hyperdrive", "POST", "subscription/usage-alerts");
    // DELETE api/hyperdrive/failover/triggers/{id}
    this.deleteFailoverTrigger = makeOperation(http, "api/hyperdrive", "DELETE", "failover/triggers/{id}");
    // DELETE api/hyperdrive/subscription/quota-notifications/{id}
    this.deleteQuotaNotification = makeOperation(http, "api/hyperdrive", "DELETE", "subscription/quota-notifications/{id}");
    // DELETE api/hyperdrive/replication/triggers/{id}
    this.deleteReplicationTrigger = makeOperation(http, "api/hyperdrive", "DELETE", "replication/triggers/{id}");
    // DELETE api/hyperdrive/subscription/usage-alerts/{id}
    this.deleteUsageAlert = makeOperation(http, "api/hyperdrive", "DELETE", "subscription/usage-alerts/{id}");
    // POST api/hyperdrive/intelligent-mode/disable
    this.disableIntelligentMode = makeOperation(http, "api/hyperdrive", "POST", "intelligent-mode/disable");
    // POST api/hyperdrive/intelligent-mode/enable
    this.enableIntelligentMode = makeOperation(http, "api/hyperdrive", "POST", "intelligent-mode/enable");
    // GET api/hyperdrive/ai/recommendations
    this.getAIRecommendations = makeOperation(http, "api/hyperdrive", "GET", "ai/recommendations");
    // GET api/hyperdrive/analytics/report
    this.getAnalyticsReport = makeOperation(http, "api/hyperdrive", "GET", "analytics/report");
    // GET api/hyperdrive/best-provider
    this.getBestProvider = makeOperation(http, "api/hyperdrive", "GET", "best-provider");
    // GET api/hyperdrive/config
    this.getConfiguration = makeOperation(http, "api/hyperdrive", "GET", "config");
    // GET api/hyperdrive/connections
    this.getConnectionCounts = makeOperation(http, "api/hyperdrive", "GET", "connections");
    // GET api/hyperdrive/costs/history
    this.getCostHistory = makeOperation(http, "api/hyperdrive", "GET", "costs/history");
    // GET api/hyperdrive/analytics/cost-optimization
    this.getCostOptimizationRecommendations = makeOperation(http, "api/hyperdrive", "GET", "analytics/cost-optimization");
    // GET api/hyperdrive/replication/cost-optimization
    this.getCostOptimizationRule = makeOperation(http, "api/hyperdrive", "GET", "replication/cost-optimization");
    // GET api/hyperdrive/costs/projections
    this.getCostProjections = makeOperation(http, "api/hyperdrive", "GET", "costs/projections");
    // GET api/hyperdrive/costs/current
    this.getCurrentCosts = makeOperation(http, "api/hyperdrive", "GET", "costs/current");
    // GET api/hyperdrive/quota/usage
    this.getCurrentUsage = makeOperation(http, "api/hyperdrive", "GET", "quota/usage");
    // GET api/hyperdrive/dashboard
    this.getDashboardData = makeOperation(http, "api/hyperdrive", "GET", "dashboard");
    // GET api/hyperdrive/data-permissions
    this.getDataPermissions = makeOperation(http, "api/hyperdrive", "GET", "data-permissions");
    // GET api/hyperdrive/replication/data-type-rules
    this.getDataTypeReplicationRules = makeOperation(http, "api/hyperdrive", "GET", "replication/data-type-rules");
    // GET api/hyperdrive/failover/escalation-rules
    this.getEscalationRules = makeOperation(http, "api/hyperdrive", "GET", "failover/escalation-rules");
    // GET api/hyperdrive/failover/rules
    this.getFailoverRules = makeOperation(http, "api/hyperdrive", "GET", "failover/rules");
    // GET api/hyperdrive/failover/predictions
    this.getFailurePredictions = makeOperation(http, "api/hyperdrive", "GET", "failover/predictions");
    // GET api/hyperdrive/providers/free
    this.getFreeProviders = makeOperation(http, "api/hyperdrive", "GET", "providers/free");
    // GET api/hyperdrive/mode
    this.getHyperDriveMode = makeOperation(http, "api/hyperdrive", "GET", "mode");
    // GET api/hyperdrive/intelligent-mode
    this.getIntelligentMode = makeOperation(http, "api/hyperdrive", "GET", "intelligent-mode");
    // GET api/hyperdrive/providers/low-cost
    this.getLowCostProviders = makeOperation(http, "api/hyperdrive", "GET", "providers/low-cost");
    // GET api/hyperdrive/metrics
    this.getMetrics = makeOperation(http, "api/hyperdrive", "GET", "metrics");
    // GET api/hyperdrive/analytics/performance-optimization
    this.getPerformanceOptimizationRecommendations = makeOperation(http, "api/hyperdrive", "GET", "analytics/performance-optimization");
    // GET api/hyperdrive/analytics/predictive/{providerType}
    this.getPredictiveAnalytics = makeOperation(http, "api/hyperdrive", "GET", "analytics/predictive/{providerType}");
    // GET api/hyperdrive/failover/provider-rules
    this.getProviderFailoverRules = makeOperation(http, "api/hyperdrive", "GET", "failover/provider-rules");
    // GET api/hyperdrive/metrics/{providerType}
    this.getProviderMetrics = makeOperation(http, "api/hyperdrive", "GET", "metrics/{providerType}");
    // GET api/hyperdrive/replication/provider-rules
    this.getProviderReplicationRules = makeOperation(http, "api/hyperdrive", "GET", "replication/provider-rules");
    // GET api/hyperdrive/quota/limits
    this.getQuotaLimits = makeOperation(http, "api/hyperdrive", "GET", "quota/limits");
    // GET api/hyperdrive/subscription/quota-notifications
    this.getQuotaNotifications = makeOperation(http, "api/hyperdrive", "GET", "subscription/quota-notifications");
    // GET api/hyperdrive/replication/rules
    this.getReplicationRules = makeOperation(http, "api/hyperdrive", "GET", "replication/rules");
    // GET api/hyperdrive/replication/schedule-rules
    this.getScheduleRules = makeOperation(http, "api/hyperdrive", "GET", "replication/schedule-rules");
    // GET api/hyperdrive/recommendations/security
    this.getSecurityRecommendations = makeOperation(http, "api/hyperdrive", "GET", "recommendations/security");
    // GET api/hyperdrive/recommendations/smart
    this.getSmartRecommendations = makeOperation(http, "api/hyperdrive", "GET", "recommendations/smart");
    // GET api/hyperdrive/status
    this.getStatus = makeOperation(http, "api/hyperdrive", "GET", "status");
    // GET api/hyperdrive/subscription/config
    this.getSubscriptionConfig = makeOperation(http, "api/hyperdrive", "GET", "subscription/config");
    // GET api/hyperdrive/subscription/usage-alerts
    this.getUsageAlerts = makeOperation(http, "api/hyperdrive", "GET", "subscription/usage-alerts");
    // POST api/hyperdrive/failover/preventive
    this.initiatePreventiveFailover = makeOperation(http, "api/hyperdrive", "POST", "failover/preventive");
    // POST api/hyperdrive/analytics/record
    this.recordAnalyticsData = makeOperation(http, "api/hyperdrive", "POST", "analytics/record");
    // POST api/hyperdrive/record-connection
    this.recordConnection = makeOperation(http, "api/hyperdrive", "POST", "record-connection");
    // POST api/hyperdrive/failover/record-failure
    this.recordFailureEvent = makeOperation(http, "api/hyperdrive", "POST", "failover/record-failure");
    // POST api/hyperdrive/ai/record-performance
    this.recordPerformanceData = makeOperation(http, "api/hyperdrive", "POST", "ai/record-performance");
    // POST api/hyperdrive/record-request
    this.recordRequest = makeOperation(http, "api/hyperdrive", "POST", "record-request");
    // POST api/hyperdrive/metrics/reset-all
    this.resetAllMetrics = makeOperation(http, "api/hyperdrive", "POST", "metrics/reset-all");
    // POST api/hyperdrive/config/reset
    this.resetConfiguration = makeOperation(http, "api/hyperdrive", "POST", "config/reset");
    // POST api/hyperdrive/metrics/{providerType}/reset
    this.resetProviderMetrics = makeOperation(http, "api/hyperdrive", "POST", "metrics/{providerType}/reset");
    // PUT api/hyperdrive/costs/limits
    this.setCostLimits = makeOperation(http, "api/hyperdrive", "PUT", "costs/limits");
    // PUT api/hyperdrive/mode
    this.setHyperDriveMode = makeOperation(http, "api/hyperdrive", "PUT", "mode");
    // PUT api/hyperdrive/config
    this.updateConfiguration = makeOperation(http, "api/hyperdrive", "PUT", "config");
    // PUT api/hyperdrive/cost/{providerType}
    this.updateCostAnalysis = makeOperation(http, "api/hyperdrive", "PUT", "cost/{providerType}");
    // PUT api/hyperdrive/replication/cost-optimization
    this.updateCostOptimizationRule = makeOperation(http, "api/hyperdrive", "PUT", "replication/cost-optimization");
    // PUT api/hyperdrive/data-permissions
    this.updateDataPermissions = makeOperation(http, "api/hyperdrive", "PUT", "data-permissions");
    // PUT api/hyperdrive/replication/data-type-rules
    this.updateDataTypeReplicationRule = makeOperation(http, "api/hyperdrive", "PUT", "replication/data-type-rules");
    // PUT api/hyperdrive/failover/escalation-rules
    this.updateEscalationRule = makeOperation(http, "api/hyperdrive", "PUT", "failover/escalation-rules");
    // PUT api/hyperdrive/failover/rules
    this.updateFailoverRules = makeOperation(http, "api/hyperdrive", "PUT", "failover/rules");
    // PUT api/hyperdrive/failover/triggers/{id}
    this.updateFailoverTrigger = makeOperation(http, "api/hyperdrive", "PUT", "failover/triggers/{id}");
    // PUT api/hyperdrive/geographic/{providerType}
    this.updateGeographicInfo = makeOperation(http, "api/hyperdrive", "PUT", "geographic/{providerType}");
    // PUT api/hyperdrive/intelligent-mode
    this.updateIntelligentMode = makeOperation(http, "api/hyperdrive", "PUT", "intelligent-mode");
    // PUT api/hyperdrive/failover/provider-rules
    this.updateProviderFailoverRule = makeOperation(http, "api/hyperdrive", "PUT", "failover/provider-rules");
    // PUT api/hyperdrive/replication/provider-rules
    this.updateProviderReplicationRule = makeOperation(http, "api/hyperdrive", "PUT", "replication/provider-rules");
    // PUT api/hyperdrive/subscription/quota-notifications/{id}
    this.updateQuotaNotification = makeOperation(http, "api/hyperdrive", "PUT", "subscription/quota-notifications/{id}");
    // PUT api/hyperdrive/replication/rules
    this.updateReplicationRules = makeOperation(http, "api/hyperdrive", "PUT", "replication/rules");
    // PUT api/hyperdrive/replication/triggers/{id}
    this.updateReplicationTrigger = makeOperation(http, "api/hyperdrive", "PUT", "replication/triggers/{id}");
    // PUT api/hyperdrive/replication/schedule-rules
    this.updateScheduleRule = makeOperation(http, "api/hyperdrive", "PUT", "replication/schedule-rules");
    // PUT api/hyperdrive/subscription/config
    this.updateSubscriptionConfig = makeOperation(http, "api/hyperdrive", "PUT", "subscription/config");
    // PUT api/hyperdrive/subscription/usage-alerts/{id}
    this.updateUsageAlert = makeOperation(http, "api/hyperdrive", "PUT", "subscription/usage-alerts/{id}");
    // POST api/hyperdrive/config/validate
    this.validateConfiguration = makeOperation(http, "api/hyperdrive", "POST", "config/validate");
  }
}

module.exports = { HyperDriveModule };
