// AUTO-GENERATED by scripts/generate-types.js - do not hand-edit.
import type { OASISResponse } from '../core/types';

export declare class HyperDriveModule {
  constructor(http: unknown);

  /** GET api/hyperdrive/quota/status */
  checkQuotaStatus(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/hyperdrive/failover/triggers */
  createFailoverTrigger(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/hyperdrive/subscription/quota-notifications */
  createQuotaNotification(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/hyperdrive/replication/triggers */
  createReplicationTrigger(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/hyperdrive/subscription/usage-alerts */
  createUsageAlert(args?: Record<string, any>): Promise<OASISResponse>;

  /** DELETE api/hyperdrive/failover/triggers/{id} */
  deleteFailoverTrigger(args?: Record<string, any>): Promise<OASISResponse>;

  /** DELETE api/hyperdrive/subscription/quota-notifications/{id} */
  deleteQuotaNotification(args?: Record<string, any>): Promise<OASISResponse>;

  /** DELETE api/hyperdrive/replication/triggers/{id} */
  deleteReplicationTrigger(args?: Record<string, any>): Promise<OASISResponse>;

  /** DELETE api/hyperdrive/subscription/usage-alerts/{id} */
  deleteUsageAlert(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/hyperdrive/intelligent-mode/disable */
  disableIntelligentMode(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/hyperdrive/intelligent-mode/enable */
  enableIntelligentMode(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/hyperdrive/ai/recommendations */
  getAIRecommendations(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/hyperdrive/analytics/report */
  getAnalyticsReport(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/hyperdrive/best-provider */
  getBestProvider(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/hyperdrive/config */
  getConfiguration(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/hyperdrive/connections */
  getConnectionCounts(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/hyperdrive/costs/history */
  getCostHistory(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/hyperdrive/analytics/cost-optimization */
  getCostOptimizationRecommendations(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/hyperdrive/replication/cost-optimization */
  getCostOptimizationRule(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/hyperdrive/costs/projections */
  getCostProjections(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/hyperdrive/costs/current */
  getCurrentCosts(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/hyperdrive/quota/usage */
  getCurrentUsage(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/hyperdrive/dashboard */
  getDashboardData(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/hyperdrive/data-permissions */
  getDataPermissions(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/hyperdrive/replication/data-type-rules */
  getDataTypeReplicationRules(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/hyperdrive/failover/escalation-rules */
  getEscalationRules(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/hyperdrive/failover/rules */
  getFailoverRules(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/hyperdrive/failover/predictions */
  getFailurePredictions(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/hyperdrive/providers/free */
  getFreeProviders(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/hyperdrive/mode */
  getHyperDriveMode(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/hyperdrive/intelligent-mode */
  getIntelligentMode(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/hyperdrive/providers/low-cost */
  getLowCostProviders(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/hyperdrive/metrics */
  getMetrics(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/hyperdrive/analytics/performance-optimization */
  getPerformanceOptimizationRecommendations(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/hyperdrive/analytics/predictive/{providerType} */
  getPredictiveAnalytics(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/hyperdrive/failover/provider-rules */
  getProviderFailoverRules(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/hyperdrive/metrics/{providerType} */
  getProviderMetrics(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/hyperdrive/replication/provider-rules */
  getProviderReplicationRules(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/hyperdrive/quota/limits */
  getQuotaLimits(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/hyperdrive/subscription/quota-notifications */
  getQuotaNotifications(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/hyperdrive/replication/rules */
  getReplicationRules(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/hyperdrive/replication/schedule-rules */
  getScheduleRules(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/hyperdrive/recommendations/security */
  getSecurityRecommendations(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/hyperdrive/recommendations/smart */
  getSmartRecommendations(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/hyperdrive/status */
  getStatus(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/hyperdrive/subscription/config */
  getSubscriptionConfig(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/hyperdrive/subscription/usage-alerts */
  getUsageAlerts(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/hyperdrive/failover/preventive */
  initiatePreventiveFailover(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/hyperdrive/analytics/record */
  recordAnalyticsData(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/hyperdrive/record-connection */
  recordConnection(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/hyperdrive/failover/record-failure */
  recordFailureEvent(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/hyperdrive/ai/record-performance */
  recordPerformanceData(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/hyperdrive/record-request */
  recordRequest(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/hyperdrive/metrics/reset-all */
  resetAllMetrics(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/hyperdrive/config/reset */
  resetConfiguration(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/hyperdrive/metrics/{providerType}/reset */
  resetProviderMetrics(args?: Record<string, any>): Promise<OASISResponse>;

  /** PUT api/hyperdrive/costs/limits */
  setCostLimits(args?: Record<string, any>): Promise<OASISResponse>;

  /** PUT api/hyperdrive/mode */
  setHyperDriveMode(args?: Record<string, any>): Promise<OASISResponse>;

  /** PUT api/hyperdrive/config */
  updateConfiguration(args?: Record<string, any>): Promise<OASISResponse>;

  /** PUT api/hyperdrive/cost/{providerType} */
  updateCostAnalysis(args?: Record<string, any>): Promise<OASISResponse>;

  /** PUT api/hyperdrive/replication/cost-optimization */
  updateCostOptimizationRule(args?: Record<string, any>): Promise<OASISResponse>;

  /** PUT api/hyperdrive/data-permissions */
  updateDataPermissions(args?: Record<string, any>): Promise<OASISResponse>;

  /** PUT api/hyperdrive/replication/data-type-rules */
  updateDataTypeReplicationRule(args?: Record<string, any>): Promise<OASISResponse>;

  /** PUT api/hyperdrive/failover/escalation-rules */
  updateEscalationRule(args?: Record<string, any>): Promise<OASISResponse>;

  /** PUT api/hyperdrive/failover/rules */
  updateFailoverRules(args?: Record<string, any>): Promise<OASISResponse>;

  /** PUT api/hyperdrive/failover/triggers/{id} */
  updateFailoverTrigger(args?: Record<string, any>): Promise<OASISResponse>;

  /** PUT api/hyperdrive/geographic/{providerType} */
  updateGeographicInfo(args?: Record<string, any>): Promise<OASISResponse>;

  /** PUT api/hyperdrive/intelligent-mode */
  updateIntelligentMode(args?: Record<string, any>): Promise<OASISResponse>;

  /** PUT api/hyperdrive/failover/provider-rules */
  updateProviderFailoverRule(args?: Record<string, any>): Promise<OASISResponse>;

  /** PUT api/hyperdrive/replication/provider-rules */
  updateProviderReplicationRule(args?: Record<string, any>): Promise<OASISResponse>;

  /** PUT api/hyperdrive/subscription/quota-notifications/{id} */
  updateQuotaNotification(args?: Record<string, any>): Promise<OASISResponse>;

  /** PUT api/hyperdrive/replication/rules */
  updateReplicationRules(args?: Record<string, any>): Promise<OASISResponse>;

  /** PUT api/hyperdrive/replication/triggers/{id} */
  updateReplicationTrigger(args?: Record<string, any>): Promise<OASISResponse>;

  /** PUT api/hyperdrive/replication/schedule-rules */
  updateScheduleRule(args?: Record<string, any>): Promise<OASISResponse>;

  /** PUT api/hyperdrive/subscription/config */
  updateSubscriptionConfig(args?: Record<string, any>): Promise<OASISResponse>;

  /** PUT api/hyperdrive/subscription/usage-alerts/{id} */
  updateUsageAlert(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/hyperdrive/config/validate */
  validateConfiguration(args?: Record<string, any>): Promise<OASISResponse>;
}
