'use strict';

// AUTO-GENERATED by scripts/generate-modules.js - do not hand-edit.
const { AvatarModule } = require('./Avatar');
const { BridgeModule } = require('./Bridge');
const { ChatModule } = require('./Chat');
const { ClanModule } = require('./Clan');
const { CompetitionModule } = require('./Competition');
const { DataModule } = require('./Data');
const { EOSIOModule } = require('./EOSIO');
const { EggsModule } = require('./Eggs');
const { FilesModule } = require('./Files');
const { GiftsModule } = require('./Gifts');
const { HealthModule } = require('./Health');
const { HolochainModule } = require('./Holochain');
const { HyperDriveModule } = require('./HyperDrive');
const { KarmaModule } = require('./Karma');
const { KeysModule } = require('./Keys');
const { MapModule } = require('./Map');
const { MessagingModule } = require('./Messaging');
const { NftModule } = require('./Nft');
const { OLandModule } = require('./OLand');
const { ONETModule } = require('./ONET');
const { ONODEModule } = require('./ONODE');
const { ProviderModule } = require('./Provider');
const { SearchModule } = require('./Search');
const { SeedsModule } = require('./Seeds');
const { SettingsModule } = require('./Settings');
const { ShareModule } = require('./Share');
const { SocialModule } = require('./Social');
const { SolanaModule } = require('./Solana');
const { StatsModule } = require('./Stats');
const { SubscriptionModule } = require('./Subscription');
const { VideoModule } = require('./Video');
const { WalletModule } = require('./Wallet');

/**
 * Attaches every generated module to the client under its lowerCamel controller
 * name (e.g. client.nft, client.wallet, client.hyperDrive). Hand-written ergonomic
 * modules (auth/avatar/data/karma) are attached separately in src/index.js and take
 * precedence where names overlap.
 */
function attachGeneratedModules(client, http) {
  client.avatar = client.avatar || new AvatarModule(http);
  client.bridge = client.bridge || new BridgeModule(http);
  client.chat = client.chat || new ChatModule(http);
  client.clan = client.clan || new ClanModule(http);
  client.competition = client.competition || new CompetitionModule(http);
  client.data = client.data || new DataModule(http);
  client.eOSIO = client.eOSIO || new EOSIOModule(http);
  client.eggs = client.eggs || new EggsModule(http);
  client.files = client.files || new FilesModule(http);
  client.gifts = client.gifts || new GiftsModule(http);
  client.health = client.health || new HealthModule(http);
  client.holochain = client.holochain || new HolochainModule(http);
  client.hyperDrive = client.hyperDrive || new HyperDriveModule(http);
  client.karma = client.karma || new KarmaModule(http);
  client.keys = client.keys || new KeysModule(http);
  client.map = client.map || new MapModule(http);
  client.messaging = client.messaging || new MessagingModule(http);
  client.nft = client.nft || new NftModule(http);
  client.oLand = client.oLand || new OLandModule(http);
  client.oNET = client.oNET || new ONETModule(http);
  client.oNODE = client.oNODE || new ONODEModule(http);
  client.provider = client.provider || new ProviderModule(http);
  client.search = client.search || new SearchModule(http);
  client.seeds = client.seeds || new SeedsModule(http);
  client.settings = client.settings || new SettingsModule(http);
  client.share = client.share || new ShareModule(http);
  client.social = client.social || new SocialModule(http);
  client.solana = client.solana || new SolanaModule(http);
  client.stats = client.stats || new StatsModule(http);
  client.subscription = client.subscription || new SubscriptionModule(http);
  client.video = client.video || new VideoModule(http);
  client.wallet = client.wallet || new WalletModule(http);
  return client;
}

module.exports = { attachGeneratedModules };
