// AUTO-GENERATED by scripts/generate-types.js - do not hand-edit.
import type { OASISResponse } from '../core/types';

export declare class KarmaModule {
  constructor(http: unknown);

  /** POST api/karma/add-karma-to-avatar/{avatarId} */
  addKarmaToAvatar(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/karma/get-karma-akashic-records-for-avatar/{avatarId} */
  getKarmaAkashicRecordsForAvatar(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/karma/get-karma-for-avatar/{avatarId} */
  getKarmaForAvatar(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/karma/get-karma-history/{avatarId} */
  getKarmaHistory(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/karma/get-karma-stats/{avatarId} */
  getKarmaStats(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/karma/get-negative-karma-weighting/{karmaType} */
  getNegativeKarmaWeighting(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/karma/get-positive-karma-weighting/{karmaType} */
  getPositiveKarmaWeighting(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/karma/remove-karma-from-avatar/{avatarId} */
  removeKarmaFromAvatar(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/karma/set-negative-karma-weighting/{karmaType}/{weighting} */
  setNegativeKarmaWeighting(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/karma/set-positive-karma-weighting/{karmaType}/{weighting} */
  setPositiveKarmaWeighting(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/karma/vote-for-negative-karma-weighting/{karmaType}/{weighting} */
  voteForNegativeKarmaWeighting(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/karma/vote-for-positive-karma-weighting/{karmaType}/{weighting} */
  voteForPositiveKarmaWeighting(args?: Record<string, any>): Promise<OASISResponse>;
}
