'use strict';

// AUTO-GENERATED by scripts/generate-modules.js from endpoints.json - do not hand-edit.
// Regenerate with: node scripts/generate-modules.js

const { makeOperation } = require('../core/routeHelper');

/**
 * Generated wrapper for api/karma (source: ONODE WebAPI KarmaController.cs).
 * Every method takes a single args object: path-template tokens (e.g. {id})
 * are consumed from it automatically; any remaining keys are sent as the
 * query string (GET/DELETE) or JSON body (POST/PUT).
 */
class KarmaModule {
  constructor(http) {
    this._http = http;

    // POST api/karma/add-karma-to-avatar/{avatarId}
    this.addKarmaToAvatar = makeOperation(http, "api/karma", "POST", "add-karma-to-avatar/{avatarId}");
    // GET api/karma/get-karma-akashic-records-for-avatar/{avatarId}
    this.getKarmaAkashicRecordsForAvatar = makeOperation(http, "api/karma", "GET", "get-karma-akashic-records-for-avatar/{avatarId}");
    // GET api/karma/get-karma-for-avatar/{avatarId}
    this.getKarmaForAvatar = makeOperation(http, "api/karma", "GET", "get-karma-for-avatar/{avatarId}");
    // GET api/karma/get-karma-history/{avatarId}
    this.getKarmaHistory = makeOperation(http, "api/karma", "GET", "get-karma-history/{avatarId}");
    // GET api/karma/get-karma-stats/{avatarId}
    this.getKarmaStats = makeOperation(http, "api/karma", "GET", "get-karma-stats/{avatarId}");
    // GET api/karma/get-negative-karma-weighting/{karmaType}
    this.getNegativeKarmaWeighting = makeOperation(http, "api/karma", "GET", "get-negative-karma-weighting/{karmaType}");
    // GET api/karma/get-positive-karma-weighting/{karmaType}
    this.getPositiveKarmaWeighting = makeOperation(http, "api/karma", "GET", "get-positive-karma-weighting/{karmaType}");
    // POST api/karma/remove-karma-from-avatar/{avatarId}
    this.removeKarmaFromAvatar = makeOperation(http, "api/karma", "POST", "remove-karma-from-avatar/{avatarId}");
    // POST api/karma/set-negative-karma-weighting/{karmaType}/{weighting}
    this.setNegativeKarmaWeighting = makeOperation(http, "api/karma", "POST", "set-negative-karma-weighting/{karmaType}/{weighting}");
    // POST api/karma/set-positive-karma-weighting/{karmaType}/{weighting}
    this.setPositiveKarmaWeighting = makeOperation(http, "api/karma", "POST", "set-positive-karma-weighting/{karmaType}/{weighting}");
    // POST api/karma/vote-for-negative-karma-weighting/{karmaType}/{weighting}
    this.voteForNegativeKarmaWeighting = makeOperation(http, "api/karma", "POST", "vote-for-negative-karma-weighting/{karmaType}/{weighting}");
    // POST api/karma/vote-for-positive-karma-weighting/{karmaType}/{weighting}
    this.voteForPositiveKarmaWeighting = makeOperation(http, "api/karma", "POST", "vote-for-positive-karma-weighting/{karmaType}/{weighting}");
  }
}

module.exports = { KarmaModule };
