// AUTO-GENERATED by scripts/generate-types.js - do not hand-edit.
import type { OASISResponse } from '../core/types';

export declare class KeysModule {
  constructor(http: unknown);

  /** POST api/keys/base58_check_decode/{data} */
  base58CheckDecode(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/keys/clear_cache */
  clearCache(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/keys/create */
  createKey(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/keys/decode_private_wif/{data} */
  decodePrivateWif(args?: Record<string, any>): Promise<OASISResponse>;

  /** DELETE api/keys/{keyId} */
  deleteKey(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/keys/encode_signature/{source} */
  encodeSignature(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/keys/generate_keypair_and_link_provider_keys_to_avatar_by_email */
  generateKeyPairAndLinkProviderKeysToAvatarByAvatarEmail(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/keys/generate_keypair_and_link_provider_keys_to_avatar_by_id */
  generateKeyPairAndLinkProviderKeysToAvatarByAvatarId(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/keys/generate_keypair_and_link_provider_keys_to_avatar_by_username */
  generateKeyPairAndLinkProviderKeysToAvatarByAvatarUsername(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/keys/generate_keypair_for_provider/{providerType} */
  generateKeyPairForProvider(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/keys/generate_keypair_with_wallet_address_and_link_provider_keys_to_avatar_by_email */
  generateKeyPairWithWalletAddressAndLinkProviderKeysToAvatarByEmail(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/keys/generate_keypair_with_wallet_address_and_link_provider_keys_to_avatar_by_id */
  generateKeyPairWithWalletAddressAndLinkProviderKeysToAvatarById(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/keys/generate_keypair_with_wallet_address_and_link_provider_keys_to_avatar_by_username */
  generateKeyPairWithWalletAddressAndLinkProviderKeysToAvatarByUsername(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/keys/generate_keypair_with_wallet_address_for_provider/{providerType} */
  generateKeyPairWithWalletAddressForProvider(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/keys/all */
  getAllKeysForAvatar(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/keys/get_all_provider_private_keys_for_avatar_by_id/{id} */
  getAllProviderPrivateKeysForAvatarById(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/keys/get_all_provider_private_keys_for_avatar_by_username/{username} */
  getAllProviderPrivateKeysForAvatarByUsername(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/keys/get_all_provider_public_keys_for_avatar_by_email/{email} */
  getAllProviderPublicKeysForAvatarByEmail(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/keys/get_all_provider_public_keys_for_avatar_by_id/{id} */
  getAllProviderPublicKeysForAvatarById(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/keys/get_all_provider_public_keys_for_avatar_by_username/{username} */
  getAllProviderPublicKeysForAvatarByUsername(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/keys/get_all_provider_unique_storage_keys_for_avatar_by_email/{email} */
  getAllProviderUniqueStorageKeysForAvatarByEmail(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/keys/get_all_provider_unique_storage_keys_for_avatar_by_id/{id} */
  getAllProviderUniqueStorageKeysForAvatarById(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/keys/get_all_provider_unique_storage_keys_for_avatar_by_username/{username} */
  getAllProviderUniqueStorageKeysForAvatarByUsername(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/keys/get_avatar_email_for_provider_public_key/{providerKey} */
  getAvatarEmailForProviderPublicKey(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/keys/get_avatar_email_for_provider_unique_storage_key/{providerKey} */
  getAvatarEmailForProviderUniqueStorageKey(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/keys/get_avatar_for_provider_private_key/{providerKey} */
  getAvatarForProviderPrivateKey(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/keys/get_avatar_for_provider_public_key/{providerKey} */
  getAvatarForProviderPublicKey(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/keys/get_avatar_for_provider_unique_storage_key/{providerKey} */
  getAvatarForProviderUniqueStorageKey(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/keys/get_avatar_id_for_provider_private_key/{providerKey} */
  getAvatarIdForProviderPrivateKey(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/keys/get_avatar_id_for_provider_public_key/{providerKey} */
  getAvatarIdForProviderPublicKey(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/keys/get_avatar_id_for_provider_unique_storage_key/{providerKey} */
  getAvatarIdForProviderUniqueStorageKey(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/keys/get_avatar_username_for_provider_private_key/{providerKey} */
  getAvatarUsernameForProviderPrivateKey(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/keys/get_avatar_username_for_provider_public_key/{providerKey} */
  getAvatarUsernameForProviderPublicKey(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/keys/get_avatar_username_for_provider_unique_storage_key/{providerKey} */
  getAvatarUsernameForProviderUniqueStorageKey(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/keys/stats */
  getKeyStats(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/keys/get_private_wifi/{source} */
  getPrivateWif(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/keys/get_provider_private_key_for_avatar_by_id */
  getProviderPrivateKeyForAvatarById(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/keys/get_provider_private_key_for_avatar_by_username */
  getProviderPrivateKeyForAvatarByUsername(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/keys/get_provider_public_keys_for_avatar_by_email */
  getProviderPublicKeysForAvatarByEmail(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/keys/get_provider_public_keys_for_avatar_by_id */
  getProviderPublicKeysForAvatarById(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/keys/get_provider_public_keys_for_avatar_by_username */
  getProviderPublicKeysForAvatarByUsername(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/keys/get_provider_unique_storage_key_for_avatar_by_email */
  getProviderUniqueStorageKeyForAvatarByEmail(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/keys/get_provider_unique_storage_key_for_avatar_by_id */
  getProviderUniqueStorageKeyForAvatarById(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/keys/get_provider_unique_storage_key_for_avatar_by_username */
  getProviderUniqueStorageKeyForAvatarByUsername(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/keys/get_public_wifi */
  getPublicWif(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/keys/{avatarId}/{eosioAccountName} */
  linkEOSIOAccountToAvatar(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/keys/{avatarId}/{holochainAgentID} */
  linkHolochainAgentIDToAvatar(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/keys/link_provider_private_key_to_avatar_by_id */
  linkProviderPrivateKeyToAvatarByAvatarId(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/keys/link_provider_private_key_to_avatar_by_email */
  linkProviderPrivateKeyToAvatarByEmail(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/keys/link_provider_private_key_to_avatar_by_username */
  linkProviderPrivateKeyToAvatarByUsername(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/keys/link_provider_public_key_to_avatar_by_id */
  linkProviderPublicKeyToAvatarByAvatarId(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/keys/link_provider_public_key_to_avatar_by_email */
  linkProviderPublicKeyToAvatarByEmail(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/keys/link_provider_public_key_to_avatar_by_username */
  linkProviderPublicKeyToAvatarByUsername(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/keys/link_provider_wallet_address_to_avatar_by_email */
  linkProviderWalletAddressToAvatarByEmail(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/keys/link_provider_wallet_address_to_avatar_by_id */
  linkProviderWalletAddressToAvatarById(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/keys/link_provider_wallet_address_to_avatar_by_username */
  linkProviderWalletAddressToAvatarByUsername(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/keys/{id:Guid}/{telosAccountName} */
  linkTelosAccountToAvatar(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/keys/ */
  linkTelosAccountToAvatar2(args?: Record<string, any>): Promise<OASISResponse>;

  /** PUT api/keys/{keyId} */
  updateKey(args?: Record<string, any>): Promise<OASISResponse>;
}
