'use strict';

// AUTO-GENERATED by scripts/generate-modules.js from endpoints.json - do not hand-edit.
// Regenerate with: node scripts/generate-modules.js

const { makeOperation } = require('../core/routeHelper');

/**
 * Generated wrapper for api/keys (source: ONODE WebAPI KeysController.cs).
 * Every method takes a single args object: path-template tokens (e.g. {id})
 * are consumed from it automatically; any remaining keys are sent as the
 * query string (GET/DELETE) or JSON body (POST/PUT).
 */
class KeysModule {
  constructor(http) {
    this._http = http;

    // POST api/keys/base58_check_decode/{data}
    this.base58CheckDecode = makeOperation(http, "api/keys", "POST", "base58_check_decode/{data}");
    // POST api/keys/clear_cache
    this.clearCache = makeOperation(http, "api/keys", "POST", "clear_cache");
    // POST api/keys/create
    this.createKey = makeOperation(http, "api/keys", "POST", "create");
    // POST api/keys/decode_private_wif/{data}
    this.decodePrivateWif = makeOperation(http, "api/keys", "POST", "decode_private_wif/{data}");
    // DELETE api/keys/{keyId}
    this.deleteKey = makeOperation(http, "api/keys", "DELETE", "{keyId}");
    // POST api/keys/encode_signature/{source}
    this.encodeSignature = makeOperation(http, "api/keys", "POST", "encode_signature/{source}");
    // POST api/keys/generate_keypair_and_link_provider_keys_to_avatar_by_email
    this.generateKeyPairAndLinkProviderKeysToAvatarByAvatarEmail = makeOperation(http, "api/keys", "POST", "generate_keypair_and_link_provider_keys_to_avatar_by_email");
    // POST api/keys/generate_keypair_and_link_provider_keys_to_avatar_by_id
    this.generateKeyPairAndLinkProviderKeysToAvatarByAvatarId = makeOperation(http, "api/keys", "POST", "generate_keypair_and_link_provider_keys_to_avatar_by_id");
    // POST api/keys/generate_keypair_and_link_provider_keys_to_avatar_by_username
    this.generateKeyPairAndLinkProviderKeysToAvatarByAvatarUsername = makeOperation(http, "api/keys", "POST", "generate_keypair_and_link_provider_keys_to_avatar_by_username");
    // POST api/keys/generate_keypair_for_provider/{providerType}
    this.generateKeyPairForProvider = makeOperation(http, "api/keys", "POST", "generate_keypair_for_provider/{providerType}");
    // POST api/keys/generate_keypair_with_wallet_address_and_link_provider_keys_to_avatar_by_email
    this.generateKeyPairWithWalletAddressAndLinkProviderKeysToAvatarByEmail = makeOperation(http, "api/keys", "POST", "generate_keypair_with_wallet_address_and_link_provider_keys_to_avatar_by_email");
    // POST api/keys/generate_keypair_with_wallet_address_and_link_provider_keys_to_avatar_by_id
    this.generateKeyPairWithWalletAddressAndLinkProviderKeysToAvatarById = makeOperation(http, "api/keys", "POST", "generate_keypair_with_wallet_address_and_link_provider_keys_to_avatar_by_id");
    // POST api/keys/generate_keypair_with_wallet_address_and_link_provider_keys_to_avatar_by_username
    this.generateKeyPairWithWalletAddressAndLinkProviderKeysToAvatarByUsername = makeOperation(http, "api/keys", "POST", "generate_keypair_with_wallet_address_and_link_provider_keys_to_avatar_by_username");
    // POST api/keys/generate_keypair_with_wallet_address_for_provider/{providerType}
    this.generateKeyPairWithWalletAddressForProvider = makeOperation(http, "api/keys", "POST", "generate_keypair_with_wallet_address_for_provider/{providerType}");
    // GET api/keys/all
    this.getAllKeysForAvatar = makeOperation(http, "api/keys", "GET", "all");
    // GET api/keys/get_all_provider_private_keys_for_avatar_by_id/{id}
    this.getAllProviderPrivateKeysForAvatarById = makeOperation(http, "api/keys", "GET", "get_all_provider_private_keys_for_avatar_by_id/{id}");
    // GET api/keys/get_all_provider_private_keys_for_avatar_by_username/{username}
    this.getAllProviderPrivateKeysForAvatarByUsername = makeOperation(http, "api/keys", "GET", "get_all_provider_private_keys_for_avatar_by_username/{username}");
    // GET api/keys/get_all_provider_public_keys_for_avatar_by_email/{email}
    this.getAllProviderPublicKeysForAvatarByEmail = makeOperation(http, "api/keys", "GET", "get_all_provider_public_keys_for_avatar_by_email/{email}");
    // GET api/keys/get_all_provider_public_keys_for_avatar_by_id/{id}
    this.getAllProviderPublicKeysForAvatarById = makeOperation(http, "api/keys", "GET", "get_all_provider_public_keys_for_avatar_by_id/{id}");
    // GET api/keys/get_all_provider_public_keys_for_avatar_by_username/{username}
    this.getAllProviderPublicKeysForAvatarByUsername = makeOperation(http, "api/keys", "GET", "get_all_provider_public_keys_for_avatar_by_username/{username}");
    // GET api/keys/get_all_provider_unique_storage_keys_for_avatar_by_email/{email}
    this.getAllProviderUniqueStorageKeysForAvatarByEmail = makeOperation(http, "api/keys", "GET", "get_all_provider_unique_storage_keys_for_avatar_by_email/{email}");
    // GET api/keys/get_all_provider_unique_storage_keys_for_avatar_by_id/{id}
    this.getAllProviderUniqueStorageKeysForAvatarById = makeOperation(http, "api/keys", "GET", "get_all_provider_unique_storage_keys_for_avatar_by_id/{id}");
    // GET api/keys/get_all_provider_unique_storage_keys_for_avatar_by_username/{username}
    this.getAllProviderUniqueStorageKeysForAvatarByUsername = makeOperation(http, "api/keys", "GET", "get_all_provider_unique_storage_keys_for_avatar_by_username/{username}");
    // GET api/keys/get_avatar_email_for_provider_public_key/{providerKey}
    this.getAvatarEmailForProviderPublicKey = makeOperation(http, "api/keys", "GET", "get_avatar_email_for_provider_public_key/{providerKey}");
    // GET api/keys/get_avatar_email_for_provider_unique_storage_key/{providerKey}
    this.getAvatarEmailForProviderUniqueStorageKey = makeOperation(http, "api/keys", "GET", "get_avatar_email_for_provider_unique_storage_key/{providerKey}");
    // GET api/keys/get_avatar_for_provider_private_key/{providerKey}
    this.getAvatarForProviderPrivateKey = makeOperation(http, "api/keys", "GET", "get_avatar_for_provider_private_key/{providerKey}");
    // GET api/keys/get_avatar_for_provider_public_key/{providerKey}
    this.getAvatarForProviderPublicKey = makeOperation(http, "api/keys", "GET", "get_avatar_for_provider_public_key/{providerKey}");
    // GET api/keys/get_avatar_for_provider_unique_storage_key/{providerKey}
    this.getAvatarForProviderUniqueStorageKey = makeOperation(http, "api/keys", "GET", "get_avatar_for_provider_unique_storage_key/{providerKey}");
    // GET api/keys/get_avatar_id_for_provider_private_key/{providerKey}
    this.getAvatarIdForProviderPrivateKey = makeOperation(http, "api/keys", "GET", "get_avatar_id_for_provider_private_key/{providerKey}");
    // GET api/keys/get_avatar_id_for_provider_public_key/{providerKey}
    this.getAvatarIdForProviderPublicKey = makeOperation(http, "api/keys", "GET", "get_avatar_id_for_provider_public_key/{providerKey}");
    // GET api/keys/get_avatar_id_for_provider_unique_storage_key/{providerKey}
    this.getAvatarIdForProviderUniqueStorageKey = makeOperation(http, "api/keys", "GET", "get_avatar_id_for_provider_unique_storage_key/{providerKey}");
    // GET api/keys/get_avatar_username_for_provider_private_key/{providerKey}
    this.getAvatarUsernameForProviderPrivateKey = makeOperation(http, "api/keys", "GET", "get_avatar_username_for_provider_private_key/{providerKey}");
    // GET api/keys/get_avatar_username_for_provider_public_key/{providerKey}
    this.getAvatarUsernameForProviderPublicKey = makeOperation(http, "api/keys", "GET", "get_avatar_username_for_provider_public_key/{providerKey}");
    // GET api/keys/get_avatar_username_for_provider_unique_storage_key/{providerKey}
    this.getAvatarUsernameForProviderUniqueStorageKey = makeOperation(http, "api/keys", "GET", "get_avatar_username_for_provider_unique_storage_key/{providerKey}");
    // GET api/keys/stats
    this.getKeyStats = makeOperation(http, "api/keys", "GET", "stats");
    // POST api/keys/get_private_wifi/{source}
    this.getPrivateWif = makeOperation(http, "api/keys", "POST", "get_private_wifi/{source}");
    // GET api/keys/get_provider_private_key_for_avatar_by_id
    this.getProviderPrivateKeyForAvatarById = makeOperation(http, "api/keys", "GET", "get_provider_private_key_for_avatar_by_id");
    // GET api/keys/get_provider_private_key_for_avatar_by_username
    this.getProviderPrivateKeyForAvatarByUsername = makeOperation(http, "api/keys", "GET", "get_provider_private_key_for_avatar_by_username");
    // GET api/keys/get_provider_public_keys_for_avatar_by_email
    this.getProviderPublicKeysForAvatarByEmail = makeOperation(http, "api/keys", "GET", "get_provider_public_keys_for_avatar_by_email");
    // GET api/keys/get_provider_public_keys_for_avatar_by_id
    this.getProviderPublicKeysForAvatarById = makeOperation(http, "api/keys", "GET", "get_provider_public_keys_for_avatar_by_id");
    // GET api/keys/get_provider_public_keys_for_avatar_by_username
    this.getProviderPublicKeysForAvatarByUsername = makeOperation(http, "api/keys", "GET", "get_provider_public_keys_for_avatar_by_username");
    // GET api/keys/get_provider_unique_storage_key_for_avatar_by_email
    this.getProviderUniqueStorageKeyForAvatarByEmail = makeOperation(http, "api/keys", "GET", "get_provider_unique_storage_key_for_avatar_by_email");
    // GET api/keys/get_provider_unique_storage_key_for_avatar_by_id
    this.getProviderUniqueStorageKeyForAvatarById = makeOperation(http, "api/keys", "GET", "get_provider_unique_storage_key_for_avatar_by_id");
    // GET api/keys/get_provider_unique_storage_key_for_avatar_by_username
    this.getProviderUniqueStorageKeyForAvatarByUsername = makeOperation(http, "api/keys", "GET", "get_provider_unique_storage_key_for_avatar_by_username");
    // POST api/keys/get_public_wifi
    this.getPublicWif = makeOperation(http, "api/keys", "POST", "get_public_wifi");
    // POST api/keys/{avatarId}/{eosioAccountName}
    this.linkEOSIOAccountToAvatar = makeOperation(http, "api/keys", "POST", "{avatarId}/{eosioAccountName}");
    // POST api/keys/{avatarId}/{holochainAgentID}
    this.linkHolochainAgentIDToAvatar = makeOperation(http, "api/keys", "POST", "{avatarId}/{holochainAgentID}");
    // POST api/keys/link_provider_private_key_to_avatar_by_id
    this.linkProviderPrivateKeyToAvatarByAvatarId = makeOperation(http, "api/keys", "POST", "link_provider_private_key_to_avatar_by_id");
    // POST api/keys/link_provider_private_key_to_avatar_by_email
    this.linkProviderPrivateKeyToAvatarByEmail = makeOperation(http, "api/keys", "POST", "link_provider_private_key_to_avatar_by_email");
    // POST api/keys/link_provider_private_key_to_avatar_by_username
    this.linkProviderPrivateKeyToAvatarByUsername = makeOperation(http, "api/keys", "POST", "link_provider_private_key_to_avatar_by_username");
    // POST api/keys/link_provider_public_key_to_avatar_by_id
    this.linkProviderPublicKeyToAvatarByAvatarId = makeOperation(http, "api/keys", "POST", "link_provider_public_key_to_avatar_by_id");
    // POST api/keys/link_provider_public_key_to_avatar_by_email
    this.linkProviderPublicKeyToAvatarByEmail = makeOperation(http, "api/keys", "POST", "link_provider_public_key_to_avatar_by_email");
    // POST api/keys/link_provider_public_key_to_avatar_by_username
    this.linkProviderPublicKeyToAvatarByUsername = makeOperation(http, "api/keys", "POST", "link_provider_public_key_to_avatar_by_username");
    // POST api/keys/link_provider_wallet_address_to_avatar_by_email
    this.linkProviderWalletAddressToAvatarByEmail = makeOperation(http, "api/keys", "POST", "link_provider_wallet_address_to_avatar_by_email");
    // POST api/keys/link_provider_wallet_address_to_avatar_by_id
    this.linkProviderWalletAddressToAvatarById = makeOperation(http, "api/keys", "POST", "link_provider_wallet_address_to_avatar_by_id");
    // POST api/keys/link_provider_wallet_address_to_avatar_by_username
    this.linkProviderWalletAddressToAvatarByUsername = makeOperation(http, "api/keys", "POST", "link_provider_wallet_address_to_avatar_by_username");
    // POST api/keys/{id:Guid}/{telosAccountName}
    this.linkTelosAccountToAvatar = makeOperation(http, "api/keys", "POST", "{id:Guid}/{telosAccountName}");
    // POST api/keys/
    this.linkTelosAccountToAvatar2 = makeOperation(http, "api/keys", "POST", "");
    // PUT api/keys/{keyId}
    this.updateKey = makeOperation(http, "api/keys", "PUT", "{keyId}");
  }
}

module.exports = { KeysModule };
