'use strict';

// AUTO-GENERATED by scripts/generate-modules.js from endpoints.json - do not hand-edit.
// Regenerate with: node scripts/generate-modules.js

const { makeOperation } = require('../core/routeHelper');

/**
 * Generated wrapper for api/keys (source: ONODE WebAPI KeysController.cs).
 * Every method takes a single args object: path-template tokens (e.g. {id})
 * are consumed from it automatically; any remaining keys are sent as the
 * query string (GET/DELETE) or JSON body (POST/PUT).
 */
class KeysModule {
  constructor(http) {
    this._http = http;

    // POST api/keys/base58-check-decode/{data}
    this.base58CheckDecode = makeOperation(http, "api/keys", "POST", "base58-check-decode/{data}");
    // POST api/keys/clear-cache
    this.clearCache = makeOperation(http, "api/keys", "POST", "clear-cache");
    // POST api/keys/create
    this.createKey = makeOperation(http, "api/keys", "POST", "create");
    // POST api/keys/decode-private-wif/{data}
    this.decodePrivateWif = makeOperation(http, "api/keys", "POST", "decode-private-wif/{data}");
    // DELETE api/keys/{keyId}
    this.deleteKey = makeOperation(http, "api/keys", "DELETE", "{keyId}");
    // POST api/keys/encode-signature/{source}
    this.encodeSignature = makeOperation(http, "api/keys", "POST", "encode-signature/{source}");
    // POST api/keys/generate-keypair-and-link-provider-keys-to-avatar-by-email
    this.generateKeyPairAndLinkProviderKeysToAvatarByAvatarEmail = makeOperation(http, "api/keys", "POST", "generate-keypair-and-link-provider-keys-to-avatar-by-email");
    // POST api/keys/generate-keypair-and-link-provider-keys-to-avatar-by-id
    this.generateKeyPairAndLinkProviderKeysToAvatarByAvatarId = makeOperation(http, "api/keys", "POST", "generate-keypair-and-link-provider-keys-to-avatar-by-id");
    // POST api/keys/generate-keypair-and-link-provider-keys-to-avatar-by-username
    this.generateKeyPairAndLinkProviderKeysToAvatarByAvatarUsername = makeOperation(http, "api/keys", "POST", "generate-keypair-and-link-provider-keys-to-avatar-by-username");
    // POST api/keys/generate-keypair-for-provider/{providerType}
    this.generateKeyPairForProvider = makeOperation(http, "api/keys", "POST", "generate-keypair-for-provider/{providerType}");
    // POST api/keys/generate-keypair-with-wallet-address-and-link-provider-keys-to-avatar-by-email
    this.generateKeyPairWithWalletAddressAndLinkProviderKeysToAvatarByEmail = makeOperation(http, "api/keys", "POST", "generate-keypair-with-wallet-address-and-link-provider-keys-to-avatar-by-email");
    // POST api/keys/generate-keypair-with-wallet-address-and-link-provider-keys-to-avatar-by-id
    this.generateKeyPairWithWalletAddressAndLinkProviderKeysToAvatarById = makeOperation(http, "api/keys", "POST", "generate-keypair-with-wallet-address-and-link-provider-keys-to-avatar-by-id");
    // POST api/keys/generate-keypair-with-wallet-address-and-link-provider-keys-to-avatar-by-username
    this.generateKeyPairWithWalletAddressAndLinkProviderKeysToAvatarByUsername = makeOperation(http, "api/keys", "POST", "generate-keypair-with-wallet-address-and-link-provider-keys-to-avatar-by-username");
    // POST api/keys/generate-keypair-with-wallet-address-for-provider/{providerType}
    this.generateKeyPairWithWalletAddressForProvider = makeOperation(http, "api/keys", "POST", "generate-keypair-with-wallet-address-for-provider/{providerType}");
    // GET api/keys/all
    this.getAllKeysForAvatar = makeOperation(http, "api/keys", "GET", "all");
    // GET api/keys/get-all-provider-private-keys-for-avatar-by-id/{id}
    this.getAllProviderPrivateKeysForAvatarById = makeOperation(http, "api/keys", "GET", "get-all-provider-private-keys-for-avatar-by-id/{id}");
    // GET api/keys/get-all-provider-private-keys-for-avatar-by-username/{username}
    this.getAllProviderPrivateKeysForAvatarByUsername = makeOperation(http, "api/keys", "GET", "get-all-provider-private-keys-for-avatar-by-username/{username}");
    // GET api/keys/get-all-provider-public-keys-for-avatar-by-email/{email}
    this.getAllProviderPublicKeysForAvatarByEmail = makeOperation(http, "api/keys", "GET", "get-all-provider-public-keys-for-avatar-by-email/{email}");
    // GET api/keys/get-all-provider-public-keys-for-avatar-by-id/{id}
    this.getAllProviderPublicKeysForAvatarById = makeOperation(http, "api/keys", "GET", "get-all-provider-public-keys-for-avatar-by-id/{id}");
    // GET api/keys/get-all-provider-public-keys-for-avatar-by-username/{username}
    this.getAllProviderPublicKeysForAvatarByUsername = makeOperation(http, "api/keys", "GET", "get-all-provider-public-keys-for-avatar-by-username/{username}");
    // GET api/keys/get-all-provider-unique-storage-keys-for-avatar-by-email/{email}
    this.getAllProviderUniqueStorageKeysForAvatarByEmail = makeOperation(http, "api/keys", "GET", "get-all-provider-unique-storage-keys-for-avatar-by-email/{email}");
    // GET api/keys/get-all-provider-unique-storage-keys-for-avatar-by-id/{id}
    this.getAllProviderUniqueStorageKeysForAvatarById = makeOperation(http, "api/keys", "GET", "get-all-provider-unique-storage-keys-for-avatar-by-id/{id}");
    // GET api/keys/get-all-provider-unique-storage-keys-for-avatar-by-username/{username}
    this.getAllProviderUniqueStorageKeysForAvatarByUsername = makeOperation(http, "api/keys", "GET", "get-all-provider-unique-storage-keys-for-avatar-by-username/{username}");
    // GET api/keys/get-avatar-email-for-provider-public-key/{providerKey}
    this.getAvatarEmailForProviderPublicKey = makeOperation(http, "api/keys", "GET", "get-avatar-email-for-provider-public-key/{providerKey}");
    // GET api/keys/get-avatar-email-for-provider-unique-storage-key/{providerKey}
    this.getAvatarEmailForProviderUniqueStorageKey = makeOperation(http, "api/keys", "GET", "get-avatar-email-for-provider-unique-storage-key/{providerKey}");
    // GET api/keys/get-avatar-for-provider-private-key/{providerKey}
    this.getAvatarForProviderPrivateKey = makeOperation(http, "api/keys", "GET", "get-avatar-for-provider-private-key/{providerKey}");
    // GET api/keys/get-avatar-for-provider-public-key/{providerKey}
    this.getAvatarForProviderPublicKey = makeOperation(http, "api/keys", "GET", "get-avatar-for-provider-public-key/{providerKey}");
    // GET api/keys/get-avatar-for-provider-unique-storage-key/{providerKey}
    this.getAvatarForProviderUniqueStorageKey = makeOperation(http, "api/keys", "GET", "get-avatar-for-provider-unique-storage-key/{providerKey}");
    // GET api/keys/get-avatar-id-for-provider-private-key/{providerKey}
    this.getAvatarIdForProviderPrivateKey = makeOperation(http, "api/keys", "GET", "get-avatar-id-for-provider-private-key/{providerKey}");
    // GET api/keys/get-avatar-id-for-provider-public-key/{providerKey}
    this.getAvatarIdForProviderPublicKey = makeOperation(http, "api/keys", "GET", "get-avatar-id-for-provider-public-key/{providerKey}");
    // GET api/keys/get-avatar-id-for-provider-unique-storage-key/{providerKey}
    this.getAvatarIdForProviderUniqueStorageKey = makeOperation(http, "api/keys", "GET", "get-avatar-id-for-provider-unique-storage-key/{providerKey}");
    // GET api/keys/get-avatar-username-for-provider-private-key/{providerKey}
    this.getAvatarUsernameForProviderPrivateKey = makeOperation(http, "api/keys", "GET", "get-avatar-username-for-provider-private-key/{providerKey}");
    // GET api/keys/get-avatar-username-for-provider-public-key/{providerKey}
    this.getAvatarUsernameForProviderPublicKey = makeOperation(http, "api/keys", "GET", "get-avatar-username-for-provider-public-key/{providerKey}");
    // GET api/keys/get-avatar-username-for-provider-unique-storage-key/{providerKey}
    this.getAvatarUsernameForProviderUniqueStorageKey = makeOperation(http, "api/keys", "GET", "get-avatar-username-for-provider-unique-storage-key/{providerKey}");
    // GET api/keys/stats
    this.getKeyStats = makeOperation(http, "api/keys", "GET", "stats");
    // POST api/keys/get-private-wifi/{source}
    this.getPrivateWif = makeOperation(http, "api/keys", "POST", "get-private-wifi/{source}");
    // GET api/keys/get-provider-private-key-for-avatar-by-id
    this.getProviderPrivateKeyForAvatarById = makeOperation(http, "api/keys", "GET", "get-provider-private-key-for-avatar-by-id");
    // GET api/keys/get-provider-private-key-for-avatar-by-username
    this.getProviderPrivateKeyForAvatarByUsername = makeOperation(http, "api/keys", "GET", "get-provider-private-key-for-avatar-by-username");
    // GET api/keys/get-provider-public-keys-for-avatar-by-email
    this.getProviderPublicKeysForAvatarByEmail = makeOperation(http, "api/keys", "GET", "get-provider-public-keys-for-avatar-by-email");
    // GET api/keys/get-provider-public-keys-for-avatar-by-id
    this.getProviderPublicKeysForAvatarById = makeOperation(http, "api/keys", "GET", "get-provider-public-keys-for-avatar-by-id");
    // GET api/keys/get-provider-public-keys-for-avatar-by-username
    this.getProviderPublicKeysForAvatarByUsername = makeOperation(http, "api/keys", "GET", "get-provider-public-keys-for-avatar-by-username");
    // GET api/keys/get-provider-unique-storage-key-for-avatar-by-email
    this.getProviderUniqueStorageKeyForAvatarByEmail = makeOperation(http, "api/keys", "GET", "get-provider-unique-storage-key-for-avatar-by-email");
    // GET api/keys/get-provider-unique-storage-key-for-avatar-by-id
    this.getProviderUniqueStorageKeyForAvatarById = makeOperation(http, "api/keys", "GET", "get-provider-unique-storage-key-for-avatar-by-id");
    // GET api/keys/get-provider-unique-storage-key-for-avatar-by-username
    this.getProviderUniqueStorageKeyForAvatarByUsername = makeOperation(http, "api/keys", "GET", "get-provider-unique-storage-key-for-avatar-by-username");
    // POST api/keys/get-public-wifi
    this.getPublicWif = makeOperation(http, "api/keys", "POST", "get-public-wifi");
    // POST api/keys/{avatarId}/{eosioAccountName}
    this.linkEOSIOAccountToAvatar = makeOperation(http, "api/keys", "POST", "{avatarId}/{eosioAccountName}");
    // POST api/keys/{avatarId}/{holochainAgentID}
    this.linkHolochainAgentIDToAvatar = makeOperation(http, "api/keys", "POST", "{avatarId}/{holochainAgentID}");
    // POST api/keys/link-provider-private-key-to-avatar-by-id
    this.linkProviderPrivateKeyToAvatarByAvatarId = makeOperation(http, "api/keys", "POST", "link-provider-private-key-to-avatar-by-id");
    // POST api/keys/link-provider-private-key-to-avatar-by-email
    this.linkProviderPrivateKeyToAvatarByEmail = makeOperation(http, "api/keys", "POST", "link-provider-private-key-to-avatar-by-email");
    // POST api/keys/link-provider-private-key-to-avatar-by-username
    this.linkProviderPrivateKeyToAvatarByUsername = makeOperation(http, "api/keys", "POST", "link-provider-private-key-to-avatar-by-username");
    // POST api/keys/link-provider-public-key-to-avatar-by-id
    this.linkProviderPublicKeyToAvatarByAvatarId = makeOperation(http, "api/keys", "POST", "link-provider-public-key-to-avatar-by-id");
    // POST api/keys/link-provider-public-key-to-avatar-by-email
    this.linkProviderPublicKeyToAvatarByEmail = makeOperation(http, "api/keys", "POST", "link-provider-public-key-to-avatar-by-email");
    // POST api/keys/link-provider-public-key-to-avatar-by-username
    this.linkProviderPublicKeyToAvatarByUsername = makeOperation(http, "api/keys", "POST", "link-provider-public-key-to-avatar-by-username");
    // POST api/keys/link-provider-wallet-address-to-avatar-by-email
    this.linkProviderWalletAddressToAvatarByEmail = makeOperation(http, "api/keys", "POST", "link-provider-wallet-address-to-avatar-by-email");
    // POST api/keys/link-provider-wallet-address-to-avatar-by-id
    this.linkProviderWalletAddressToAvatarById = makeOperation(http, "api/keys", "POST", "link-provider-wallet-address-to-avatar-by-id");
    // POST api/keys/link-provider-wallet-address-to-avatar-by-username
    this.linkProviderWalletAddressToAvatarByUsername = makeOperation(http, "api/keys", "POST", "link-provider-wallet-address-to-avatar-by-username");
    // POST api/keys/{id:Guid}/{telosAccountName}
    this.linkTelosAccountToAvatar = makeOperation(http, "api/keys", "POST", "{id:Guid}/{telosAccountName}");
    // POST api/keys/
    this.linkTelosAccountToAvatar2 = makeOperation(http, "api/keys", "POST", "");
    // PUT api/keys/{keyId}
    this.updateKey = makeOperation(http, "api/keys", "PUT", "{keyId}");
  }
}

module.exports = { KeysModule };
