// AUTO-GENERATED by scripts/generate-types.js - do not hand-edit.
import type { OASISResponse } from '../core/types';

export declare class LevelModule {
  constructor(http: unknown);

  /** GET api/level/lookup */
  getLevelLookup(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/level/calculate/{karma} */
  calculateLevelFromKarma(args?: Record<string, any>): Promise<OASISResponse>;
}
