// AUTO-GENERATED by scripts/generate-types.js - do not hand-edit.
import type { OASISResponse } from '../core/types';

export declare class MapModule {
  constructor(http: unknown);

  /** POST api/map/CreateAndDrawRouteOnMapBetweenHolons/{holonDNA} */
  createAndDrawRouteOnMapBetweenHolons(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/map/CreateAndDrawRouteOnMapBeweenPoints/{points} */
  createAndDrawRouteOnMapBeweenPoints(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/map/Draw2DSpriteOnHUD/{sprite}/{x}/{y} */
  draw2DSpriteOnHUD(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/map/Draw2DSpriteOnMap/{sprite}/{x}/{y} */
  draw2DSpriteOnMap(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/map/Draw3DObjectOnMap/{obj}/{x}/{y} */
  draw3DObjectOnMap(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/map/stats */
  getMapStats(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/map/nearby */
  getNearbyLocations(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/map/visit-history */
  getVisitHistory(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/map/HighlightBuildingOnMap/{building} */
  highlightBuildingOnMap(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/map/PamMapDown/{value} */
  pamMapDown(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/map/PamMapLeft/{value} */
  pamMapLeft(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/map/PamMapRight/{value} */
  pamMapRight(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/map/PamMapUp/{value} */
  pamMapUp(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/map/search */
  search(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/map/search-locations */
  searchLocations(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/map/SelectBuildingOnMap/{building} */
  selectBuildingOnMap(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/map/SelectHolonOnMap/{holon} */
  selectHolonOnMap(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/map/SelectQuestOnMap/{quest} */
  selectQuestOnMap(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/map/visit/{locationId} */
  visitLocation(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/map/ZoomMapIn/{value} */
  zoomMapIn(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/map/ZoomMapOut/{value} */
  zoomMapOut(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/map/ZoomToHolonOnMap/{holon} */
  zoomToHolonOnMap(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/map/ZoomToQuestOnMap/{quest} */
  zoomToQuestOnMap(args?: Record<string, any>): Promise<OASISResponse>;
}
