// AUTO-GENERATED by scripts/generate-types.js - do not hand-edit.
import type { OASISResponse } from '../core/types';

export declare class MessagingModule {
  constructor(http: unknown);

  /** GET api/messaging/conversation/{otherAvatarId} */
  getConversation(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/messaging/messages */
  getMessages(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/messaging/notifications */
  getNotifications(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/messaging/mark-messages-read */
  markMessagesAsRead(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/messaging/mark-notifications-read */
  markNotificationsAsRead(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/messaging/send-message-to-avatar/{toAvatarId} */
  sendMessageToAvatar(args?: Record<string, any>): Promise<OASISResponse>;
}
