'use strict';

// AUTO-GENERATED by scripts/generate-modules.js from endpoints.json - do not hand-edit.
// Regenerate with: node scripts/generate-modules.js

const { makeOperation } = require('../core/routeHelper');

/**
 * Generated wrapper for api/messaging (source: ONODE WebAPI MessagingController.cs).
 * Every method takes a single args object: path-template tokens (e.g. {id})
 * are consumed from it automatically; any remaining keys are sent as the
 * query string (GET/DELETE) or JSON body (POST/PUT).
 */
class MessagingModule {
  constructor(http) {
    this._http = http;

    // Get api/messaging/conversation/{otherAvatarId}
    this.getConversation = makeOperation(http, "api/messaging", "GET", "conversation/{otherAvatarId}");
    // Get api/messaging/messages
    this.getMessages = makeOperation(http, "api/messaging", "GET", "messages");
    // Get api/messaging/notifications
    this.getNotifications = makeOperation(http, "api/messaging", "GET", "notifications");
    // Post api/messaging/mark-messages-read
    this.markMessagesAsRead = makeOperation(http, "api/messaging", "POST", "mark-messages-read");
    // Post api/messaging/mark-notifications-read
    this.markNotificationsAsRead = makeOperation(http, "api/messaging", "POST", "mark-notifications-read");
    // Post api/messaging/send-message-to-avatar/{toAvatarId}
    this.sendMessageToAvatar = makeOperation(http, "api/messaging", "POST", "send-message-to-avatar/{toAvatarId}");
  }
}

module.exports = { MessagingModule };
