'use strict';

// AUTO-GENERATED by scripts/generate-modules.js from endpoints.json - do not hand-edit.
// Regenerate with: node scripts/generate-modules.js

const { makeOperation } = require('../core/routeHelper');

/**
 * Generated wrapper for api/nft (source: ONODE WebAPI NftController.cs).
 * Every method takes a single args object: path-template tokens (e.g. {id})
 * are consumed from it automatically; any remaining keys are sent as the
 * query string (GET/DELETE) or JSON body (POST/PUT).
 */
class NftModule {
  constructor(http) {
    this._http = http;

    // Post api/nft/
    this.collectGeoNFTAsync = makeOperation(http, "api/nft", "POST", "");
    // Post api/nft/
    this.collectNFTAsync = makeOperation(http, "api/nft", "POST", "");
    // Post api/nft/
    this.createWeb4NFTCollectionAsync = makeOperation(http, "api/nft", "POST", "");
    // Post api/nft/
    this.exportWeb4NFTAsync = makeOperation(http, "api/nft", "POST", "");
    // Post api/nft/
    this.exportWeb4NFTToFileAsync = makeOperation(http, "api/nft", "POST", "");
    // Get api/nft/
    this.getNFTProviderFromProviderType = makeOperation(http, "api/nft", "GET", "");
    // Post api/nft/
    this.importWeb3NFTAsync = makeOperation(http, "api/nft", "POST", "");
    // Post api/nft/
    this.importWeb4NFTAsync = makeOperation(http, "api/nft", "POST", "");
    // Post api/nft/
    this.importWeb4NFTFromFileAsync = makeOperation(http, "api/nft", "POST", "");
    // Get api/nft/
    this.loadAllGeoNFTsAsync = makeOperation(http, "api/nft", "GET", "");
    // Get api/nft/
    this.loadAllGeoNFTsForMintAddressAsync = makeOperation(http, "api/nft", "GET", "");
    // Get api/nft/
    this.loadAllWeb3NFTsAsync = makeOperation(http, "api/nft", "GET", "");
    // Get api/nft/
    this.loadAllWeb3NFTsForAvatarAsync = makeOperation(http, "api/nft", "GET", "");
    // Get api/nft/
    this.loadAllWeb3NFTsForMintAddressAsync = makeOperation(http, "api/nft", "GET", "");
    // Get api/nft/
    this.loadAllWeb4GeoNFTsAsync = makeOperation(http, "api/nft", "GET", "");
    // Get api/nft/
    this.loadAllWeb4GeoNFTsForAvatarAsync = makeOperation(http, "api/nft", "GET", "");
    // Get api/nft/
    this.loadAllWeb4NFTsAsync = makeOperation(http, "api/nft", "GET", "");
    // Get api/nft/
    this.loadAllWeb4NFTsForAvatarAsync = makeOperation(http, "api/nft", "GET", "");
    // Get api/nft/
    this.loadAllWeb4NFTsForMintAddressAsync = makeOperation(http, "api/nft", "GET", "");
    // Get api/nft/
    this.loadWeb3NftByHashAsync = makeOperation(http, "api/nft", "GET", "");
    // Get api/nft/
    this.loadWeb3NftByIdAsync = makeOperation(http, "api/nft", "GET", "");
    // Get api/nft/
    this.loadWeb4NftByHashAsync = makeOperation(http, "api/nft", "GET", "");
    // Get api/nft/
    this.loadWeb4NftByIdAsync = makeOperation(http, "api/nft", "GET", "");
    // Post api/nft/
    this.mintAndPlaceGeoNFTAsync = makeOperation(http, "api/nft", "POST", "");
    // Post api/nft/
    this.mintNftAsync = makeOperation(http, "api/nft", "POST", "");
    // Post api/nft/
    this.placeGeoNFTAsync = makeOperation(http, "api/nft", "POST", "");
    // Post api/nft/
    this.remintNftAsync = makeOperation(http, "api/nft", "POST", "");
    // Get api/nft/
    this.searchWeb4GeoNFTsAsync = makeOperation(http, "api/nft", "GET", "");
    // Get api/nft/
    this.searchWeb4NFTCollectionsAsync = makeOperation(http, "api/nft", "GET", "");
    // Get api/nft/
    this.searchWeb4NFTsAsync = makeOperation(http, "api/nft", "GET", "");
    // Post api/nft/
    this.sendNFTAsync = makeOperation(http, "api/nft", "POST", "");
    // Post api/nft/
    this.updateWeb4NftAsync = makeOperation(http, "api/nft", "POST", "");
  }
}

module.exports = { NftModule };
