// AUTO-GENERATED by scripts/generate-types.js - do not hand-edit.
import type { OASISResponse } from '../core/types';

export declare class NftModule {
  constructor(http: unknown);

  /** POST api/nft/ */
  collectGeoNFTAsync(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/nft/ */
  collectNFTAsync(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/nft/ */
  createWeb4NFTCollectionAsync(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/nft/ */
  exportWeb4NFTAsync(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/nft/ */
  exportWeb4NFTToFileAsync(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/nft/ */
  getNFTProviderFromProviderType(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/nft/ */
  importWeb3NFTAsync(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/nft/ */
  importWeb4NFTAsync(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/nft/ */
  importWeb4NFTFromFileAsync(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/nft/ */
  loadAllGeoNFTsAsync(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/nft/ */
  loadAllGeoNFTsForMintAddressAsync(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/nft/ */
  loadAllWeb3NFTsAsync(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/nft/ */
  loadAllWeb3NFTsForAvatarAsync(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/nft/ */
  loadAllWeb3NFTsForMintAddressAsync(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/nft/ */
  loadAllWeb4GeoNFTsAsync(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/nft/ */
  loadAllWeb4GeoNFTsForAvatarAsync(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/nft/ */
  loadAllWeb4NFTsAsync(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/nft/ */
  loadAllWeb4NFTsForAvatarAsync(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/nft/ */
  loadAllWeb4NFTsForMintAddressAsync(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/nft/ */
  loadWeb3NftByHashAsync(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/nft/ */
  loadWeb3NftByIdAsync(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/nft/ */
  loadWeb4NftByHashAsync(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/nft/ */
  loadWeb4NftByIdAsync(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/nft/ */
  mintAndPlaceGeoNFTAsync(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/nft/ */
  mintNftAsync(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/nft/ */
  placeGeoNFTAsync(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/nft/ */
  remintNftAsync(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/nft/ */
  searchWeb4GeoNFTsAsync(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/nft/ */
  searchWeb4NFTCollectionsAsync(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/nft/ */
  searchWeb4NFTsAsync(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/nft/ */
  sendNFTAsync(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/nft/ */
  updateWeb4NftAsync(args?: Record<string, any>): Promise<OASISResponse>;
}
