'use strict';

// AUTO-GENERATED by scripts/generate-modules.js from endpoints.json - do not hand-edit.
// Regenerate with: node scripts/generate-modules.js

const { makeOperation } = require('../core/routeHelper');

/**
 * Generated wrapper for api/oapp (source: ONODE WebAPI OAPPController.cs).
 * Every method takes a single args object: path-template tokens (e.g. {id})
 * are consumed from it automatically; any remaining keys are sent as the
 * query string (GET/DELETE) or JSON body (POST/PUT).
 */
class OAPPModule {
  constructor(http) {
    this._http = http;

    // GET api/oapp/installed
    this.getAllOAPPsInstalledForCurrentLoggedInAvatar = makeOperation(http, "api/oapp", "GET", "installed");
    // GET api/oapp/stats
    this.getOAPPStats = makeOperation(http, "api/oapp", "GET", "stats");
    // POST api/oapp/install
    this.installOAPP = makeOperation(http, "api/oapp", "POST", "install");
    // DELETE api/oapp/{oappId}
    this.uninstallOAPP = makeOperation(http, "api/oapp", "DELETE", "{oappId}");
    // PUT api/oapp/{oappId}
    this.updateOAPP = makeOperation(http, "api/oapp", "PUT", "{oappId}");
  }
}

module.exports = { OAPPModule };
