'use strict';

// AUTO-GENERATED by scripts/generate-modules.js from endpoints.json - do not hand-edit.
// Regenerate with: node scripts/generate-modules.js

const { makeOperation } = require('../core/routeHelper');

/**
 * Generated wrapper for api/oland (source: ONODE WebAPI OLandController.cs).
 * Every method takes a single args object: path-template tokens (e.g. {id})
 * are consumed from it automatically; any remaining keys are sent as the
 * query string (GET/DELETE) or JSON body (POST/PUT).
 */
class OLandModule {
  constructor(http) {
    this._http = http;

    // Post api/oland/
    this.deleteOlandAsync = makeOperation(http, "api/oland", "POST", "");
    // Get api/oland/
    this.getOlandPrice = makeOperation(http, "api/oland", "GET", "");
    // Get api/oland/
    this.loadAllOlands = makeOperation(http, "api/oland", "GET", "");
    // Get api/oland/
    this.loadOlandAsync = makeOperation(http, "api/oland", "GET", "");
    // Post api/oland/
    this.purchaseOland = makeOperation(http, "api/oland", "POST", "");
    // Post api/oland/
    this.saveOlandAsync = makeOperation(http, "api/oland", "POST", "");
    // Post api/oland/
    this.updateOlandAsync = makeOperation(http, "api/oland", "POST", "");
  }
}

module.exports = { OLandModule };
