// AUTO-GENERATED by scripts/generate-types.js - do not hand-edit.
import type { OASISResponse } from '../core/types';

export declare class OLandModule {
  constructor(http: unknown);

  /** POST api/oland/ */
  deleteOlandAsync(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/oland/ */
  getOlandPrice(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/oland/ */
  loadAllOlands(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/oland/ */
  loadOlandAsync(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/oland/ */
  purchaseOland(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/oland/ */
  saveOlandAsync(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/oland/ */
  updateOlandAsync(args?: Record<string, any>): Promise<OASISResponse>;
}
