// AUTO-GENERATED by scripts/generate-types.js - do not hand-edit.
import type { OASISResponse } from '../core/types';

export declare class ONETModule {
  constructor(http: unknown);

  /** POST api/v1/onet/network/broadcast */
  broadcastMessage(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/v1/onet/network/connect */
  connectToNode(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/v1/onet/network/disconnect */
  disconnectFromNode(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/v1/onet/network/nodes */
  getConnectedNodes(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/v1/onet/network/stats */
  getNetworkStats(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/v1/onet/network/status */
  getNetworkStatus(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/v1/onet/network/topology */
  getNetworkTopology(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/v1/onet/oasisdna */
  getOASISDNA(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/v1/onet/network/start */
  startNetwork(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/v1/onet/network/stop */
  stopNetwork(args?: Record<string, any>): Promise<OASISResponse>;

  /** PUT api/v1/onet/oasisdna */
  updateOASISDNA(args?: Record<string, any>): Promise<OASISResponse>;
}
