'use strict';

// AUTO-GENERATED by scripts/generate-modules.js from endpoints.json - do not hand-edit.
// Regenerate with: node scripts/generate-modules.js

const { makeOperation } = require('../core/routeHelper');

/**
 * Generated wrapper for api/v1/onet (source: ONODE WebAPI ONETController.cs).
 * Every method takes a single args object: path-template tokens (e.g. {id})
 * are consumed from it automatically; any remaining keys are sent as the
 * query string (GET/DELETE) or JSON body (POST/PUT).
 */
class ONETModule {
  constructor(http) {
    this._http = http;

    // POST api/v1/onet/network/broadcast
    this.broadcastMessage = makeOperation(http, "api/v1/onet", "POST", "network/broadcast");
    // POST api/v1/onet/network/connect
    this.connectToNode = makeOperation(http, "api/v1/onet", "POST", "network/connect");
    // POST api/v1/onet/network/disconnect
    this.disconnectFromNode = makeOperation(http, "api/v1/onet", "POST", "network/disconnect");
    // GET api/v1/onet/network/nodes
    this.getConnectedNodes = makeOperation(http, "api/v1/onet", "GET", "network/nodes");
    // GET api/v1/onet/network/stats
    this.getNetworkStats = makeOperation(http, "api/v1/onet", "GET", "network/stats");
    // GET api/v1/onet/network/status
    this.getNetworkStatus = makeOperation(http, "api/v1/onet", "GET", "network/status");
    // GET api/v1/onet/network/topology
    this.getNetworkTopology = makeOperation(http, "api/v1/onet", "GET", "network/topology");
    // GET api/v1/onet/oasisdna
    this.getOASISDNA = makeOperation(http, "api/v1/onet", "GET", "oasisdna");
    // POST api/v1/onet/network/start
    this.startNetwork = makeOperation(http, "api/v1/onet", "POST", "network/start");
    // POST api/v1/onet/network/stop
    this.stopNetwork = makeOperation(http, "api/v1/onet", "POST", "network/stop");
    // PUT api/v1/onet/oasisdna
    this.updateOASISDNA = makeOperation(http, "api/v1/onet", "PUT", "oasisdna");
  }
}

module.exports = { ONETModule };
