// AUTO-GENERATED by scripts/generate-types.js - do not hand-edit.
import type { OASISResponse } from '../core/types';

export declare class ONODEModule {
  constructor(http: unknown);

  /** GET api/v1/onode/peers */
  getConnectedPeers(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/v1/onode/config */
  getNodeConfig(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/v1/onode/info */
  getNodeInfo(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/v1/onode/logs */
  getNodeLogs(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/v1/onode/metrics */
  getNodeMetrics(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/v1/onode/stats */
  getNodeStats(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/v1/onode/status */
  getNodeStatus(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/v1/onode/oasisdna */
  getOASISDNA(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/v1/onode/restart */
  restartNode(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/v1/onode/start */
  startNode(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/v1/onode/stop */
  stopNode(args?: Record<string, any>): Promise<OASISResponse>;

  /** PUT api/v1/onode/config */
  updateNodeConfig(args?: Record<string, any>): Promise<OASISResponse>;

  /** PUT api/v1/onode/oasisdna */
  updateOASISDNA(args?: Record<string, any>): Promise<OASISResponse>;
}
