'use strict';

// AUTO-GENERATED by scripts/generate-modules.js from endpoints.json - do not hand-edit.
// Regenerate with: node scripts/generate-modules.js

const { makeOperation } = require('../core/routeHelper');

/**
 * Generated wrapper for api/v1/onode (source: ONODE WebAPI ONODEController.cs).
 * Every method takes a single args object: path-template tokens (e.g. {id})
 * are consumed from it automatically; any remaining keys are sent as the
 * query string (GET/DELETE) or JSON body (POST/PUT).
 */
class ONODEModule {
  constructor(http) {
    this._http = http;

    // GET api/v1/onode/peers
    this.getConnectedPeers = makeOperation(http, "api/v1/onode", "GET", "peers");
    // GET api/v1/onode/config
    this.getNodeConfig = makeOperation(http, "api/v1/onode", "GET", "config");
    // GET api/v1/onode/info
    this.getNodeInfo = makeOperation(http, "api/v1/onode", "GET", "info");
    // GET api/v1/onode/logs
    this.getNodeLogs = makeOperation(http, "api/v1/onode", "GET", "logs");
    // GET api/v1/onode/metrics
    this.getNodeMetrics = makeOperation(http, "api/v1/onode", "GET", "metrics");
    // GET api/v1/onode/stats
    this.getNodeStats = makeOperation(http, "api/v1/onode", "GET", "stats");
    // GET api/v1/onode/status
    this.getNodeStatus = makeOperation(http, "api/v1/onode", "GET", "status");
    // GET api/v1/onode/oasisdna
    this.getOASISDNA = makeOperation(http, "api/v1/onode", "GET", "oasisdna");
    // POST api/v1/onode/restart
    this.restartNode = makeOperation(http, "api/v1/onode", "POST", "restart");
    // POST api/v1/onode/start
    this.startNode = makeOperation(http, "api/v1/onode", "POST", "start");
    // POST api/v1/onode/stop
    this.stopNode = makeOperation(http, "api/v1/onode", "POST", "stop");
    // PUT api/v1/onode/config
    this.updateNodeConfig = makeOperation(http, "api/v1/onode", "PUT", "config");
    // PUT api/v1/onode/oasisdna
    this.updateOASISDNA = makeOperation(http, "api/v1/onode", "PUT", "oasisdna");
  }
}

module.exports = { ONODEModule };
