// AUTO-GENERATED by scripts/generate-types.js - do not hand-edit.
import type { OASISResponse } from '../core/types';

export declare class ProviderModule {
  constructor(http: unknown);

  /** POST api/provider/activate-provider/{providerType} */
  activateProvider(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/provider/deactivate-provider/{providerType} */
  deActivateProvider(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/provider/get-all-registered-network-providers */
  getAllRegisteredNetworkProviders(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/provider/get-all-registered-providers */
  getAllRegisteredProviders(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/provider/get-all-registered-providers-for-category/{category} */
  getAllRegisteredProvidersForCategory(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/provider/get-all-registered-provider-types */
  getAllRegisteredProviderTypes(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/provider/get-all-registered-renderer-providers */
  getAllRegisteredRendererProviders(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/provider/get-all-registered-storage-providers */
  getAllRegisteredStorageProviders(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/provider/get-current-storage-provider */
  getCurrentStorageProvider(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/provider/get-current-storage-provider-type */
  getCurrentStorageProviderType(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/provider/get-providers-that-are-auto-replicating */
  getProvidersThatAreAutoReplicating(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/provider/get-providers-that-have-auto-fail-over-enabled */
  getProvidersThatHaveAutoFailOverEnabled(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/provider/get-providers-that-have-auto-load-balance-enabled */
  getProvidersThatHaveAutoLoadBalanceEnabled(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/provider/get-registered-provider/{providerType} */
  getRegisteredProvider(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/provider/is-provider-registered/{providerType} */
  isProviderRegistered(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/provider/register-provider/{provider} */
  registerProvider(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/provider/register-providers/{providers} */
  registerProviders(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/provider/register-provider-type/{providerType} */
  registerProviderType(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/provider/register-provider-types/{providerTypes} */
  registerProviderTypes(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/provider/set-and-activate-current-storage-provider/{providerType}/{setGlobally} */
  setAndActivateCurrentStorageProvider(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/provider/set-auto-fail-over-for-all-providers/{addToFailOverList} */
  setAutoFailOverForAllProviders(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/provider/set-auto-fail-over-for-list-of-providers/{addToFailOverList}/{providerTypes} */
  setAutoFailOverForListOfProviders(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/provider/set-auto-load-balance-for-all-providers/{addToLoadBalanceList} */
  setAutoLoadBalanceForAllProviders(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/provider/set-auto-load-balance-for-list-of-providers/{addToLoadBalanceList}/{providerTypes} */
  setAutoLoadBalanceForListOfProviders(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/provider/set-auto-replicate-for-all-providers/{autoReplicate} */
  setAutoReplicateForAllProviders(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/provider/set-auto-replicate-for-list-of-providers/{autoReplicate}/{providerTypes} */
  setAutoReplicateForListOfProviders(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/provider/set-provider-config/{providerType}/{connectionString} */
  setProviderConfig(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/provider/unregister-provider/{provider} */
  unRegisterProvider(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/provider/unregister-providers/{providers} */
  unRegisterProviders(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/provider/unregister-provider-type/{providerType} */
  unRegisterProviderType(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/provider/unregister-provider-types/{providerTypes} */
  unRegisterProviderTypes(args?: Record<string, any>): Promise<OASISResponse>;
}
