// AUTO-GENERATED by scripts/generate-types.js - do not hand-edit.
import type { OASISResponse } from '../core/types';

export declare class SearchModule {
  constructor(http: unknown);

  /** GET api/search/{searchParams} */
  get(args?: Record<string, any>): Promise<OASISResponse>;
}
