'use strict';

// AUTO-GENERATED by scripts/generate-modules.js from endpoints.json - do not hand-edit.
// Regenerate with: node scripts/generate-modules.js

const { makeOperation } = require('../core/routeHelper');

/**
 * Generated wrapper for api/search (source: ONODE WebAPI SearchController.cs).
 * Every method takes a single args object: path-template tokens (e.g. {id})
 * are consumed from it automatically; any remaining keys are sent as the
 * query string (GET/DELETE) or JSON body (POST/PUT).
 */
class SearchModule {
  constructor(http) {
    this._http = http;

    // Get api/search/{searchParams}
    this.get = makeOperation(http, "api/search", "GET", "{searchParams}");
  }
}

module.exports = { SearchModule };
