// AUTO-GENERATED by scripts/generate-types.js - do not hand-edit.
import type { OASISResponse } from '../core/types';

export declare class SeedsModule {
  constructor(http: unknown);

  /** GET api/seeds/me/transactions */
  getMySeedTransactions(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/seeds/avatar/{avatarId}/transactions */
  getSeedTransactionsForAvatar(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/seeds/save-seed-transaction */
  saveSeedTransaction(args?: Record<string, any>): Promise<OASISResponse>;
}
