'use strict';

// AUTO-GENERATED by scripts/generate-modules.js from endpoints.json - do not hand-edit.
// Regenerate with: node scripts/generate-modules.js

const { makeOperation } = require('../core/routeHelper');

/**
 * Generated wrapper for api/seeds (source: ONODE WebAPI SeedsController.cs).
 * Every method takes a single args object: path-template tokens (e.g. {id})
 * are consumed from it automatically; any remaining keys are sent as the
 * query string (GET/DELETE) or JSON body (POST/PUT).
 */
class SeedsModule {
  constructor(http) {
    this._http = http;

    // GET api/seeds/me/transactions
    this.getMySeedTransactions = makeOperation(http, "api/seeds", "GET", "me/transactions");
    // GET api/seeds/avatar/{avatarId}/transactions
    this.getSeedTransactionsForAvatar = makeOperation(http, "api/seeds", "GET", "avatar/{avatarId}/transactions");
    // POST api/seeds/save-seed-transaction
    this.saveSeedTransaction = makeOperation(http, "api/seeds", "POST", "save-seed-transaction");
  }
}

module.exports = { SeedsModule };
