// AUTO-GENERATED by scripts/generate-types.js - do not hand-edit.
import type { OASISResponse } from '../core/types';

export declare class SettingsModule {
  constructor(http: unknown);

  /** GET api/settings/get-all-settings-for-current-logged-in-avatar */
  getAllSettingsForCurrentLoggedInAvatar(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/settings/hyperdrive-settings */
  getHyperDriveSettings(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/settings/notification-preferences */
  getNotificationPreferences(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/settings/privacy-settings */
  getPrivacySettings(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/settings/subscription-settings */
  getSubscriptionSettings(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/settings/system-config */
  getSystemConfig(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/settings/system-settings */
  getSystemSettings(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/settings/version */
  getVersion(args?: Record<string, any>): Promise<OASISResponse>;

  /** PUT api/settings/hyperdrive-settings */
  updateHyperDriveSettings(args?: Record<string, any>): Promise<OASISResponse>;

  /** PUT api/settings/notification-preferences */
  updateNotificationPreferences(args?: Record<string, any>): Promise<OASISResponse>;

  /** PUT api/settings/privacy-settings */
  updatePrivacySettings(args?: Record<string, any>): Promise<OASISResponse>;

  /** PUT api/settings/update-settings */
  updateSettings(args?: Record<string, any>): Promise<OASISResponse>;

  /** PUT api/settings/subscription-settings */
  updateSubscriptionSettings(args?: Record<string, any>): Promise<OASISResponse>;

  /** PUT api/settings/system-settings */
  updateSystemSettings(args?: Record<string, any>): Promise<OASISResponse>;
}
