// AUTO-GENERATED by scripts/generate-types.js - do not hand-edit.
import type { OASISResponse } from '../core/types';

export declare class ShareModule {
  constructor(http: unknown);

  /** GET api/share/share-holon/{holonId:guid}/{avatarId:guid} */
  shareHolon(args?: Record<string, any>): Promise<OASISResponse>;
}
