'use strict';

// AUTO-GENERATED by scripts/generate-modules.js from endpoints.json - do not hand-edit.
// Regenerate with: node scripts/generate-modules.js

const { makeOperation } = require('../core/routeHelper');

/**
 * Generated wrapper for api/share (source: ONODE WebAPI ShareController.cs).
 * Every method takes a single args object: path-template tokens (e.g. {id})
 * are consumed from it automatically; any remaining keys are sent as the
 * query string (GET/DELETE) or JSON body (POST/PUT).
 */
class ShareModule {
  constructor(http) {
    this._http = http;

    // Get api/share/share-holon/{holonId:guid}/{avatarId:guid}
    this.shareHolon = makeOperation(http, "api/share", "GET", "share-holon/{holonId:guid}/{avatarId:guid}");
  }
}

module.exports = { ShareModule };
