'use strict';

// AUTO-GENERATED by scripts/generate-modules.js from endpoints.json - do not hand-edit.
// Regenerate with: node scripts/generate-modules.js

const { makeOperation } = require('../core/routeHelper');

/**
 * Generated wrapper for api/social (source: ONODE WebAPI SocialController.cs).
 * Every method takes a single args object: path-template tokens (e.g. {id})
 * are consumed from it automatically; any remaining keys are sent as the
 * query string (GET/DELETE) or JSON body (POST/PUT).
 */
class SocialModule {
  constructor(http) {
    this._http = http;

    // GET api/social/registered-providers
    this.getRegisteredProviders = makeOperation(http, "api/social", "GET", "registered-providers");
    // GET api/social/social-feed
    this.getSocialFeed = makeOperation(http, "api/social", "GET", "social-feed");
    // POST api/social/register-social-provider
    this.registerSocialProvider = makeOperation(http, "api/social", "POST", "register-social-provider");
    // POST api/social/share-holon
    this.shareHolon = makeOperation(http, "api/social", "POST", "share-holon");
  }
}

module.exports = { SocialModule };
