// AUTO-GENERATED by scripts/generate-types.js - do not hand-edit.
import type { OASISResponse } from '../core/types';

export declare class SocialModule {
  constructor(http: unknown);

  /** GET api/social/registered-providers */
  getRegisteredProviders(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/social/social-feed */
  getSocialFeed(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/social/register-social-provider */
  registerSocialProvider(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/social/share-holon */
  shareHolon(args?: Record<string, any>): Promise<OASISResponse>;
}
