// AUTO-GENERATED by scripts/generate-types.js - do not hand-edit.
import type { OASISResponse } from '../core/types';

export declare class SolanaModule {
  constructor(http: unknown);

  /** POST api/solana/ */
  mintNft(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/solana/ */
  sendTransaction(args?: Record<string, any>): Promise<OASISResponse>;
}
