'use strict';

// AUTO-GENERATED by scripts/generate-modules.js from endpoints.json - do not hand-edit.
// Regenerate with: node scripts/generate-modules.js

const { makeOperation } = require('../core/routeHelper');

/**
 * Generated wrapper for api/solana (source: ONODE WebAPI SolanaController.cs).
 * Every method takes a single args object: path-template tokens (e.g. {id})
 * are consumed from it automatically; any remaining keys are sent as the
 * query string (GET/DELETE) or JSON body (POST/PUT).
 */
class SolanaModule {
  constructor(http) {
    this._http = http;

    // POST api/solana/Mint
    this.mintNft = makeOperation(http, "api/solana", "POST", "Mint");
    // POST api/solana/Send
    this.sendTransaction = makeOperation(http, "api/solana", "POST", "Send");
  }
}

module.exports = { SolanaModule };
