// AUTO-GENERATED by scripts/generate-types.js - do not hand-edit.
import type { OASISResponse } from '../core/types';

export declare class StatsModule {
  constructor(http: unknown);

  /** GET api/stats/chat-stats/{avatarId} */
  getChatStats(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/stats/gift-stats/{avatarId} */
  getGiftStats(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/stats/karma-history/{avatarId} */
  getKarmaHistory(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/stats/karma-stats/{avatarId} */
  getKarmaStats(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/stats/key-stats/{avatarId} */
  getKeyStats(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/stats/leaderboard-stats/{avatarId} */
  getLeaderboardStats(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/stats/get-stats-for-current-logged-in-avatar */
  getStatsForCurrentLoggedInAvatar(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/stats/system-stats */
  getSystemStats(args?: Record<string, any>): Promise<OASISResponse>;
}
