'use strict';

// AUTO-GENERATED by scripts/generate-modules.js from endpoints.json - do not hand-edit.
// Regenerate with: node scripts/generate-modules.js

const { makeOperation } = require('../core/routeHelper');

/**
 * Generated wrapper for api/stats (source: ONODE WebAPI StatsController.cs).
 * Every method takes a single args object: path-template tokens (e.g. {id})
 * are consumed from it automatically; any remaining keys are sent as the
 * query string (GET/DELETE) or JSON body (POST/PUT).
 */
class StatsModule {
  constructor(http) {
    this._http = http;

    // Get api/stats/chat-stats/{avatarId}
    this.getChatStats = makeOperation(http, "api/stats", "GET", "chat-stats/{avatarId}");
    // Get api/stats/gift-stats/{avatarId}
    this.getGiftStats = makeOperation(http, "api/stats", "GET", "gift-stats/{avatarId}");
    // Get api/stats/karma-history/{avatarId}
    this.getKarmaHistory = makeOperation(http, "api/stats", "GET", "karma-history/{avatarId}");
    // Get api/stats/karma-stats/{avatarId}
    this.getKarmaStats = makeOperation(http, "api/stats", "GET", "karma-stats/{avatarId}");
    // Get api/stats/key-stats/{avatarId}
    this.getKeyStats = makeOperation(http, "api/stats", "GET", "key-stats/{avatarId}");
    // Get api/stats/leaderboard-stats/{avatarId}
    this.getLeaderboardStats = makeOperation(http, "api/stats", "GET", "leaderboard-stats/{avatarId}");
    // Get api/stats/get-stats-for-current-logged-in-avatar
    this.getStatsForCurrentLoggedInAvatar = makeOperation(http, "api/stats", "GET", "get-stats-for-current-logged-in-avatar");
    // Get api/stats/system-stats
    this.getSystemStats = makeOperation(http, "api/stats", "GET", "system-stats");
  }
}

module.exports = { StatsModule };
