// AUTO-GENERATED by scripts/generate-types.js - do not hand-edit.
import type { OASISResponse } from '../core/types';

export declare class SubscriptionModule {
  constructor(http: unknown);

  /** POST api/subscription/check-hyperdrive-quota */
  checkHyperDriveQuota(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/subscription/checkout/session */
  createCheckoutSession(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/subscription/hyperdrive-usage */
  getHyperDriveUsage(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/subscription/orders/me */
  getMyOrders(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/subscription/subscriptions/me */
  getMySubscriptions(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/subscription/plans */
  getPlans(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/subscription/usage */
  getUsage(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/subscription/webhooks/stripe */
  stripeWebhook(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/subscription/toggle-pay-as-you-go */
  togglePayAsYouGo(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/subscription/update-hyperdrive-config */
  updateHyperDriveConfig(args?: Record<string, any>): Promise<OASISResponse>;
}
