'use strict';

// AUTO-GENERATED by scripts/generate-modules.js from endpoints.json - do not hand-edit.
// Regenerate with: node scripts/generate-modules.js

const { makeOperation } = require('../core/routeHelper');

/**
 * Generated wrapper for api/subscription (source: ONODE WebAPI SubscriptionController.cs).
 * Every method takes a single args object: path-template tokens (e.g. {id})
 * are consumed from it automatically; any remaining keys are sent as the
 * query string (GET/DELETE) or JSON body (POST/PUT).
 */
class SubscriptionModule {
  constructor(http) {
    this._http = http;

    // POST api/subscription/check-hyperdrive-quota
    this.checkHyperDriveQuota = makeOperation(http, "api/subscription", "POST", "check-hyperdrive-quota");
    // POST api/subscription/checkout/session
    this.createCheckoutSession = makeOperation(http, "api/subscription", "POST", "checkout/session");
    // GET api/subscription/hyperdrive-usage
    this.getHyperDriveUsage = makeOperation(http, "api/subscription", "GET", "hyperdrive-usage");
    // GET api/subscription/orders/me
    this.getMyOrders = makeOperation(http, "api/subscription", "GET", "orders/me");
    // GET api/subscription/subscriptions/me
    this.getMySubscriptions = makeOperation(http, "api/subscription", "GET", "subscriptions/me");
    // GET api/subscription/plans
    this.getPlans = makeOperation(http, "api/subscription", "GET", "plans");
    // GET api/subscription/usage
    this.getUsage = makeOperation(http, "api/subscription", "GET", "usage");
    // POST api/subscription/webhooks/stripe
    this.stripeWebhook = makeOperation(http, "api/subscription", "POST", "webhooks/stripe");
    // POST api/subscription/toggle-pay-as-you-go
    this.togglePayAsYouGo = makeOperation(http, "api/subscription", "POST", "toggle-pay-as-you-go");
    // POST api/subscription/update-hyperdrive-config
    this.updateHyperDriveConfig = makeOperation(http, "api/subscription", "POST", "update-hyperdrive-config");
  }
}

module.exports = { SubscriptionModule };
