'use strict';

// AUTO-GENERATED by scripts/generate-modules.js from endpoints.json - do not hand-edit.
// Regenerate with: node scripts/generate-modules.js

const { makeOperation } = require('../core/routeHelper');

/**
 * Generated wrapper for api/telos (source: ONODE WebAPI TelosController.cs).
 * Every method takes a single args object: path-template tokens (e.g. {id})
 * are consumed from it automatically; any remaining keys are sent as the
 * query string (GET/DELETE) or JSON body (POST/PUT).
 */
class TelosModule {
  constructor(http) {
    this._http = http;

    // GET api/telos/get-avatar-for-telos-account-name
    this.getAvatarForTelosAccountName = makeOperation(http, "api/telos", "GET", "get-avatar-for-telos-account-name");
    // GET api/telos/get-avatar-id-for-telos-account-name
    this.getAvatarIdForTelosAccountName = makeOperation(http, "api/telos", "GET", "get-avatar-id-for-telos-account-name");
    // GET api/telos/get-balance-for-avatar
    this.getBalanceForAvatar = makeOperation(http, "api/telos", "GET", "get-balance-for-avatar");
    // GET api/telos/get-balance-for-telos-account
    this.getBalanceForTelosAccount = makeOperation(http, "api/telos", "GET", "get-balance-for-telos-account");
    // GET api/telos/get-telos-accoun-private-key-for-avatar
    this.getTelosAccounPrivateKeyForAvatar = makeOperation(http, "api/telos", "GET", "get-telos-accoun-private-key-for-avatar");
    // GET api/telos/get-telos-account
    this.getTelosAccount = makeOperation(http, "api/telos", "GET", "get-telos-account");
    // GET api/telos/get-telos-account-for-avatar
    this.getTelosAccountForAvatar = makeOperation(http, "api/telos", "GET", "get-telos-account-for-avatar");
    // GET api/telos/get-telos-account-names-for-avatar
    this.getTelosAccountNameForAvatar = makeOperation(http, "api/telos", "GET", "get-telos-account-names-for-avatar");
    // POST api/telos/{avatarId}/{telosAccountName}
    this.linkTelosAccountToAvatar = makeOperation(http, "api/telos", "POST", "{avatarId}/{telosAccountName}");
  }
}

module.exports = { TelosModule };
