// AUTO-GENERATED by scripts/generate-types.js - do not hand-edit.
import type { OASISResponse } from '../core/types';

export declare class VideoModule {
  constructor(http: unknown);

  /** POST api/video/end-call/{callId} */
  endVideoCall(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/video/join-call/{callId} */
  joinVideoCall(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/video/start-video-call */
  startVideoCall(args?: Record<string, any>): Promise<OASISResponse>;
}
