'use strict';

// AUTO-GENERATED by scripts/generate-modules.js from endpoints.json - do not hand-edit.
// Regenerate with: node scripts/generate-modules.js

const { makeOperation } = require('../core/routeHelper');

/**
 * Generated wrapper for api/video (source: ONODE WebAPI VideoController.cs).
 * Every method takes a single args object: path-template tokens (e.g. {id})
 * are consumed from it automatically; any remaining keys are sent as the
 * query string (GET/DELETE) or JSON body (POST/PUT).
 */
class VideoModule {
  constructor(http) {
    this._http = http;

    // POST api/video/end-call/{callId}
    this.endVideoCall = makeOperation(http, "api/video", "POST", "end-call/{callId}");
    // POST api/video/join-call/{callId}
    this.joinVideoCall = makeOperation(http, "api/video", "POST", "join-call/{callId}");
    // POST api/video/start-video-call
    this.startVideoCall = makeOperation(http, "api/video", "POST", "start-video-call");
  }
}

module.exports = { VideoModule };
