// AUTO-GENERATED by scripts/generate-types.js - do not hand-edit.
import type { OASISResponse } from '../core/types';

export declare class WalletModule {
  constructor(http: unknown);

  /** POST api/wallet/avatar/email/{email}/create-wallet */
  createWalletForAvatarByEmailAsync(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/wallet/avatar/{avatarId}/create-wallet */
  createWalletForAvatarByIdAsync(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/wallet/avatar/username/{username}/create-wallet */
  createWalletForAvatarByUsernameAsync(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/wallet/avatar/email/{email}/default-wallet */
  getAvatarDefaultWalletByEmailAsync(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/wallet/avatar/{id}/default-wallet */
  getAvatarDefaultWalletByIdAsync(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/wallet/avatar/username/{username}/default-wallet/{showOnlyDefault}/{decryptPrivateKeys} */
  getAvatarDefaultWalletByUsernameAsync(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/wallet/avatar/{avatarId}/portfolio/value */
  getPortfolioValueAsync(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/wallet/supported-chains */
  getSupportedChains(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/wallet/avatar/{avatarId}/wallet/{walletId}/analytics */
  getWalletAnalyticsAsync(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/wallet/avatar/{avatarId}/wallets/chain/{chain} */
  getWalletsByChainAsync(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/wallet/find-wallet */
  getWalletThatPublicKeyBelongsTo(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/wallet/avatar/{avatarId}/wallet/{walletId}/tokens */
  getWalletTokensAsync(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/wallet/avatar/email/{email}/import/private-key */
  importWalletUsingPrivateKeyByEmail(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/wallet/avatar/{avatarId}/import/private-key */
  importWalletUsingPrivateKeyById(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/wallet/avatar/username/{username}/import/private-key */
  importWalletUsingPrivateKeyByUsername(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/wallet/avatar/email/{email}/import/public-key */
  importWalletUsingPublicKeyByEmail(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/wallet/avatar/{avatarId}/import/public-key */
  importWalletUsingPublicKeyById(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/wallet/avatar/username/{username}/import/public-key */
  importWalletUsingPublicKeyByUsername(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/wallet/avatar/email/{email}/wallets */
  loadProviderWalletsForAvatarByEmailAsync(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/wallet/avatar/{id}/wallets/{showOnlyDefault}/{decryptPrivateKeys} */
  loadProviderWalletsForAvatarByIdAsync(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/wallet/avatar/username/{username}/wallets/{showOnlyDefault}/{decryptPrivateKeys} */
  loadProviderWalletsForAvatarByUsernameAsync(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/wallet/avatar/email/{email}/wallets */
  saveProviderWalletsForAvatarByEmailAsync(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/wallet/avatar/{id}/wallets */
  saveProviderWalletsForAvatarByIdAsync(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/wallet/avatar/username/{username}/wallets */
  saveProviderWalletsForAvatarByUsernameAsync(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/wallet/send_token */
  sendTokenAsync(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/wallet/avatar/email/{email}/default-wallet/{walletId} */
  setAvatarDefaultWalletByEmailAsync(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/wallet/avatar/{id}/default-wallet/{walletId} */
  setAvatarDefaultWalletByIdAsync(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/wallet/avatar/username/{username}/default-wallet/{walletId} */
  setAvatarDefaultWalletByUsernameAsync(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/wallet/transfer */
  transferBetweenWalletsAsync(args?: Record<string, any>): Promise<OASISResponse>;

  /** PUT api/wallet/avatar/email/{email}/wallet/{walletId} */
  updateWalletForAvatarByEmailAsync(args?: Record<string, any>): Promise<OASISResponse>;

  /** PUT api/wallet/avatar/{avatarId}/wallet/{walletId} */
  updateWalletForAvatarByIdAsync(args?: Record<string, any>): Promise<OASISResponse>;

  /** PUT api/wallet/avatar/username/{username}/wallet/{walletId} */
  updateWalletForAvatarByUsernameAsync(args?: Record<string, any>): Promise<OASISResponse>;
}
